import type { ItemDefinition } from '../../../engine';

export const COTW_BELTS: ItemDefinition[] = [
  {
    id: 'braided_sinew_cord',
    name: 'Braided Sinew Cord',
    unidentifiedName: 'Crude Rope Belt',
    category: 'container',
    slot: 'waist',
    tier: 1,
    minFloor: 2,
    weight: 250,
    bulk: 300,
    identified: true,
    description: 'A braided cord of animal sinew with loops for a quick draught or tool.',
    value: 20,
    itemType: 'container',
    containerConfig: {
      containerType: 'belt',
      maxSlots: 2,
      maxWeightCapacity: 4000,
      maxBulkCapacity: 1500,
      acceptedCategories: ['wand', 'potion', 'scroll', 'consumable'],
    },
  },
  {
    id: 'tool_hung_smiths_girdle',
    name: "Tool-Hung Smith's Girdle",
    unidentifiedName: 'Studded Tool Belt',
    category: 'container',
    slot: 'waist',
    tier: 2,
    minFloor: 12,
    weight: 900,
    bulk: 800,
    stats: { defenseBonus: 1 },
    identified: false,
    description: 'Heavy hide belt equipped with reinforced brass rings and potion sheaths for quick access during forge work.',
    value: 85,
    itemType: 'container',
    containerConfig: {
      containerType: 'belt',
      maxSlots: 5,
      maxWeightCapacity: 8000,
      maxBulkCapacity: 3000,
      acceptedCategories: ['wand', 'potion', 'scroll', 'consumable'],
    },
  },
  {
    id: 'ember_pouch_sash',
    name: 'Ember-Pouch Sash',
    unidentifiedName: 'Cinder-Embroidered Sash',
    category: 'container',
    slot: 'waist',
    tier: 3,
    minFloor: 21,
    weight: 600,
    bulk: 600,
    stats: { defenseBonus: 1 },
    quality: 'enchanted',
    identified: false,
    description: 'Asbestos-threaded silk sash holding embers of forge heat, imbuing consumables with ignited vigor that sears nearby foes upon quaffing.',
    value: 170,
    itemType: 'container',
    containerConfig: {
      containerType: 'belt',
      maxSlots: 4,
      maxWeightCapacity: 7000,
      maxBulkCapacity: 2500,
      acceptedCategories: ['wand', 'potion', 'scroll', 'consumable'],
    },
  },
  {
    id: 'silverlode_money_belt',
    name: 'Silverlode Money-Belt',
    unidentifiedName: 'Heavy Buckled Belt',
    category: 'container',
    slot: 'waist',
    tier: 3,
    minFloor: 28,
    weight: 800,
    bulk: 700,
    stats: { defenseBonus: 2 },
    quality: 'enchanted',
    identified: false,
    description: 'Concealed compartment belt lined with silver weave that prevents pouch-slitting thieves and greedy sprites from stealing coin.',
    value: 240,
    itemType: 'container',
    containerConfig: {
      containerType: 'belt',
      maxSlots: 4,
      maxWeightCapacity: 9000,
      maxBulkCapacity: 3000,
      acceptedCategories: ['wand', 'potion', 'scroll', 'consumable', 'currency'],
    },
  },
  {
    id: 'girdle_of_thryms_line',
    name: "Girdle of Thrym's Line",
    unidentifiedName: 'Colossal Iron-Banded Belt',
    category: 'container',
    slot: 'waist',
    tier: 4,
    minFloor: 46,
    weight: 2500,
    bulk: 2000,
    stats: { attackBonus: 6, defenseBonus: 3 },
    quality: 'artifact',
    identified: false,
    description: 'A colossal girdle forged in the primordial frost of Jötunheim. Vastly amplifies physical striking force and load-bearing endurance.',
    value: 650,
    itemType: 'container',
    containerConfig: {
      containerType: 'belt',
      maxSlots: 6,
      maxWeightCapacity: 25000,
      maxBulkCapacity: 8000,
      acceptedCategories: ['wand', 'potion', 'scroll', 'consumable'],
    },
  },
];
