import type { ItemDefinition } from '../../../engine';

export const COTW_CLOAKS: ItemDefinition[] = [
  {
    id: 'tattered_travelers_wrap',
    name: "Tattered Traveler's Wrap",
    unidentifiedName: 'Frayed Wool Mantle',
    category: 'cloak',
    slot: 'overgarment',
    tier: 1,
    minFloor: 2,
    weight: 500,
    bulk: 800,
    stats: { defenseBonus: 1 },
    identified: true,
    description: 'Weather-beaten traveling wool. Protects from drafty caverns without hindering movement.',
    value: 15,
  },
  {
    id: 'ash_weave_mantle',
    name: 'Ash-Weave Mantle',
    unidentifiedName: 'Smoky Grey Cloak',
    category: 'cloak',
    slot: 'overgarment',
    tier: 2,
    minFloor: 11,
    weight: 800,
    bulk: 1000,
    stats: { defenseBonus: 2 },
    identified: false,
    description: 'Woven with volcanic wool and soot-dusted ash, blending into dim passages and obscuring the wearer from watchful eyes.',
    value: 70,
  },
  {
    id: 'huldras_nettlespun_cloak',
    name: "Huldra's Nettlespun Cloak",
    unidentifiedName: 'Bramble-Weft Cloak',
    category: 'cloak',
    slot: 'overgarment',
    tier: 2,
    minFloor: 16,
    weight: 700,
    bulk: 900,
    stats: { defenseBonus: 3 },
    quality: 'enchanted',
    identified: false,
    description: 'Spun from stinging wild nettles gathered by forest huldras. Conceals the wearer from woodland spirits and beasts.',
    value: 110,
  },
  {
    id: 'sap_sealed_cape',
    name: 'Sap-Sealed Cape',
    unidentifiedName: 'Amber-Coated Cape',
    category: 'cloak',
    slot: 'overgarment',
    tier: 4,
    minFloor: 34,
    weight: 1800,
    bulk: 1400,
    stats: { defenseBonus: 5, speedBonus: -1 },
    quality: 'enchanted',
    identified: false,
    description: 'Heavy mantle stiffened with translucent golden Yggdrasil tree sap, forming an impervious seal against caustic bile and rot.',
    value: 240,
  },
  {
    id: 'shroud_of_the_unburied',
    name: 'Shroud of the Unburied',
    unidentifiedName: 'Mourning Grave Linen',
    category: 'cloak',
    slot: 'overgarment',
    tier: 4,
    minFloor: 44,
    weight: 600,
    bulk: 800,
    stats: { defenseBonus: 6 },
    quality: 'artifact',
    identified: false,
    description: 'Grave-linen saturated with sorrowful spirit essence. Undead entities pause in reverence or confusion before striking.',
    value: 420,
  },
];
