import type { ItemDefinition } from '../../../engine';

export const COTW_CONSUMABLES: ItemDefinition[] = [
  // ==========================================
  // CURATIVES (5)
  // ==========================================
  {
    id: 'birch_tar_poultice',
    name: 'Birch-Tar Poultice',
    unidentifiedName: 'Black Herbal Paste',
    category: 'consumable',
    tier: 1,
    minFloor: 2,
    weight: 150,
    bulk: 100,
    identified: true,
    description: 'Antiseptic birch-tar and moss paste that seals wounds and neutralizes venom instantly, temporarily numbing the limb.',
    value: 25,
    itemType: 'potion',
    potionConfig: {
      effects: [
        { type: 'cure_status', status: 'poison' },
        { type: 'apply_status', status: 'slow', duration: 3 },
      ],
    },
  },
  {
    id: 'hearth_broth_flask',
    name: 'Hearth-Broth Flask',
    unidentifiedName: 'Warm Ceramic Flask',
    category: 'consumable',
    tier: 1,
    minFloor: 2,
    weight: 250,
    bulk: 150,
    identified: true,
    description: 'Savory root and bone broth simmered over village hearthfires, restoring 20 Hit Points as it warms chilled veins.',
    value: 20,
    itemType: 'potion',
    potionConfig: {
      potionType: 'health',
      potency: 20,
      effects: [{ type: 'restore_hp', amount: 20 }],
    },
  },
  {
    id: 'bog_myrtle_tonic',
    name: 'Bog-Myrtle Tonic',
    unidentifiedName: 'Murky Amber Draft',
    category: 'consumable',
    tier: 2,
    minFloor: 11,
    weight: 200,
    bulk: 120,
    identified: false,
    description: 'Fermented swamp herbs and honey that restore 30 Mana while briefly muddling mental clarity.',
    value: 45,
    itemType: 'potion',
    potionConfig: {
      potionType: 'mana',
      potency: 30,
      effects: [{ type: 'restore_mana', amount: 30 }],
    },
  },
  {
    id: 'marrow_rich_stew',
    name: 'Marrow-Rich Stew',
    unidentifiedName: 'Heavy Clay Pot',
    category: 'consumable',
    tier: 3,
    minFloor: 26,
    weight: 400,
    bulk: 250,
    identified: false,
    description: 'Hearty mammoth marrow stew that restores 60 Hit Points and grants bolstered vitality.',
    value: 90,
    itemType: 'potion',
    potionConfig: {
      potionType: 'health',
      potency: 60,
      effects: [{ type: 'restore_hp', amount: 60 }],
    },
  },
  {
    id: 'draught_of_thawed_blood',
    name: 'Draught of Thawed Blood',
    unidentifiedName: 'Steaming Crimson Vial',
    category: 'consumable',
    tier: 4,
    minFloor: 34,
    weight: 300,
    bulk: 180,
    quality: 'enchanted',
    identified: false,
    description: 'A steaming primordial draft that purges all afflictions, curses, and debilitating venoms from the bloodstream.',
    value: 180,
    itemType: 'potion',
    potionConfig: {
      effects: [
        { type: 'cure_status', status: 'all' },
        { type: 'apply_status', status: 'slow', duration: 4 },
      ],
    },
  },

  // ==========================================
  // COMBAT & TACTICAL (6)
  // ==========================================
  {
    id: 'bog_iron_whetstone',
    name: 'Bog-Iron Whetstone',
    unidentifiedName: 'Rough Brown Whetstone',
    category: 'consumable',
    tier: 1,
    minFloor: 3,
    weight: 350,
    bulk: 200,
    identified: false,
    description: 'Restores keen sharpness to a melee weapon and coats the edge with oxidizing mineral grit that causes bleeding wounds.',
    value: 35,
  },
  {
    id: 'bellows_skin_canteen',
    name: 'Bellows-Skin Canteen',
    unidentifiedName: 'Black Leather Bellows',
    category: 'consumable',
    tier: 2,
    minFloor: 12,
    weight: 500,
    bulk: 400,
    identified: false,
    description: 'Discharges a dense plume of soot and ash, blinding adjacent monsters and obscuring sightlines.',
    value: 65,
    itemType: 'potion',
    potionConfig: {
      effects: [
        { type: 'radial_status', radius: 3, tags: ['monster'], status: 'blindness', duration: 3 },
      ],
    },
  },
  {
    id: 'ice_stave_rune_tablet',
    name: 'Ice-Stave Rune Tablet',
    unidentifiedName: 'Inscribed Ice Tablet',
    category: 'consumable',
    tier: 2,
    minFloor: 14,
    weight: 400,
    bulk: 300,
    identified: false,
    description: 'Smashed upon the dungeon floor, instantly flash-freezing liquid pools and fluids into impassable glacial rime.',
    value: 80,
  },
  {
    id: 'zealots_sun_flare',
    name: "Zealot's Sun-Flare",
    unidentifiedName: 'Wrapped Solar Spindle',
    category: 'consumable',
    tier: 3,
    minFloor: 20,
    weight: 300,
    bulk: 200,
    identified: false,
    description: 'A radiant incendiary projectile that explodes in a burst of scorching holy fire, illuminating dark corridors and awakening dormant beasts.',
    value: 120,
    itemType: 'potion',
    potionConfig: {
      effects: [
        { type: 'radial_status', radius: 3, tags: ['monster'], status: 'burning', duration: 4 },
      ],
    },
    hooks: [
      {
        event: 'onHit',
        chance: 1.0,
        action: {
          type: 'bonusDamage',
          amount: 25,
          element: 'fire',
        },
        description: "✦ Zealot's Sun-Flare detonates in scorching radiant fire!",
      },
    ],
  },
  {
    id: 'vial_of_choke_damp',
    name: 'Vial of Choke-Damp',
    unidentifiedName: 'Sealed Green Phial',
    category: 'consumable',
    tier: 3,
    minFloor: 27,
    weight: 250,
    bulk: 150,
    identified: false,
    description: 'Pressurized subterranean mine gas that shatters into an expanding, lingering vapor of suffocating poison.',
    value: 140,
    itemType: 'potion',
    potionConfig: {
      effects: [
        { type: 'radial_status', radius: 3, tags: ['monster', 'player'], status: 'poison', duration: 5 },
      ],
    },
  },
  {
    id: 'grave_salt_pouch',
    name: 'Grave-Salt Pouch',
    unidentifiedName: 'Pouch of Coarse Grey Salt',
    category: 'consumable',
    tier: 4,
    minFloor: 35,
    weight: 300,
    bulk: 200,
    identified: false,
    description: 'Blessed warding salt scattered in an arc across floor stones, preventing draugr and restless shades from crossing the barrier.',
    value: 160,
  },

  // ==========================================
  // UTILITY & KNOWLEDGE (5)
  // ==========================================
  {
    id: 'grave_wax_candle',
    name: 'Grave-Wax Candle',
    unidentifiedName: 'Pale Tallow Candle',
    category: 'consumable',
    tier: 2,
    minFloor: 16,
    weight: 150,
    bulk: 100,
    quality: 'enchanted',
    identified: false,
    description: 'A corpse-fat candle that burns with an eerie pale blue light, exposing secret doors and hidden barrow illusions while luring restless dead.',
    value: 95,
  },
  {
    id: 'mead_of_the_corpse_tongue',
    name: 'Mead of the Corpse-Tongue',
    unidentifiedName: 'Black Fermented Horn',
    category: 'consumable',
    tier: 2,
    minFloor: 17,
    weight: 350,
    bulk: 250,
    quality: 'enchanted',
    identified: false,
    description: 'A heady hallucinogenic brew that allows deciphering ancient runes and anticipating hostile paths while blurring standard vision.',
    value: 130,
    itemType: 'potion',
    potionConfig: {
      effects: [
        { type: 'apply_status', status: 'sensory_masked', duration: 10 },
      ],
    },
  },
  {
    id: 'rune_scratched_bark_map',
    name: 'Rune-Scratched Bark Map',
    unidentifiedName: 'Scratched Birch Bark',
    category: 'consumable',
    tier: 2,
    minFloor: 13,
    weight: 50,
    bulk: 40,
    identified: false,
    description: 'Ancient surveyor markings on birch bark that project the architectural layout of the current dungeon floor into the mind.',
    value: 75,
    itemType: 'scroll',
    scrollConfig: {
      spellId: 'magic_mapping',
    },
  },
  {
    id: 'duergar_lodestone',
    name: 'Duergar Lodestone',
    unidentifiedName: 'Magnetic Iron Pebble',
    category: 'consumable',
    tier: 3,
    minFloor: 22,
    weight: 200,
    bulk: 150,
    identified: false,
    description: 'An attuned lodestone that turns irresistibly toward subterranean drafts and descending staircases before dissolving into dust.',
    value: 110,
  },
  {
    id: 'wand_of_the_ironwood_bough',
    name: 'Wand of the Ironwood Bough',
    unidentifiedName: 'Gnarled Twig Wand',
    category: 'consumable',
    tier: 4,
    minFloor: 36,
    weight: 400,
    bulk: 250,
    quality: 'enchanted',
    identified: false,
    description: 'A petrified wand from the Ironwood boughs that shoots grasping tendrils of root, immobilizing a target in place.',
    value: 290,
    itemType: 'wand',
    wandConfig: {
      spellId: 'entangle',
      charges: 6,
      maxCharges: 6,
    },
  },
];
