import type { ItemDefinition } from '../../../engine';

export const COTW_CONTAINERS: ItemDefinition[] = [
  {
    id: 'sealskin_rucksack',
    name: 'Sealskin Rucksack',
    unidentifiedName: 'Fur-Trimmed Pack',
    category: 'container',
    slot: 'pack',
    tier: 1,
    minFloor: 2,
    weight: 1200,
    bulk: 1800,
    identified: true,
    description: 'A durable water-repellent rucksack stitched from cured seal hide. Standard adventurer carrying capacity.',
    value: 30,
    itemType: 'container',
    containerConfig: {
      containerType: 'pack',
      maxWeightCapacity: 25000,
      maxBulkCapacity: 20000,
    },
  },
  {
    id: 'dwarven_tool_frame',
    name: 'Dwarven Tool-Frame',
    unidentifiedName: 'Rigid Iron Pack Frame',
    category: 'container',
    slot: 'pack',
    tier: 2,
    minFloor: 12,
    weight: 3000,
    bulk: 3500,
    stats: { speedBonus: -1 },
    identified: false,
    description: 'An engineered external frame forged from lightweight iron truss-work. Greatly expands pack capacity, though heavily loaded trips hinder agility.',
    value: 120,
    itemType: 'container',
    containerConfig: {
      containerType: 'pack',
      maxWeightCapacity: 45000,
      maxBulkCapacity: 35000,
    },
  },
  {
    id: 'world_bark_satchel',
    name: 'World-Bark Satchel',
    unidentifiedName: 'Gnarled Wood Satchel',
    category: 'container',
    slot: 'pack',
    tier: 4,
    minFloor: 35,
    weight: 1800,
    bulk: 2200,
    quality: 'artifact',
    identified: false,
    description: 'A miraculous field satchel grown from living hollowed Yggdrasil bark. Holds vast supplies and insulates rations and gear from acidic decay.',
    value: 450,
    itemType: 'container',
    containerConfig: {
      containerType: 'pack',
      maxWeightCapacity: 55000,
      maxBulkCapacity: 45000,
    },
  },
  {
    id: 'leather_coin_pouch',
    name: 'Leather Coin-Pouch',
    unidentifiedName: 'Small Leather Pouch',
    category: 'container',
    slot: 'purse',
    tier: 1,
    minFloor: 2,
    weight: 80,
    bulk: 120,
    identified: true,
    description: 'A modest drawstring pouch of soft doe-skin suited for keeping silver and gold coins organized.',
    value: 15,
    itemType: 'container',
    containerConfig: {
      containerType: 'purse',
      maxWeightCapacity: 5000,
      maxBulkCapacity: 800,
      acceptedCategories: ['currency'],
    },
  },
  {
    id: 'quicksilver_lined_purse',
    name: 'Quicksilver-Lined Purse',
    unidentifiedName: 'Heavy Metallic Purse',
    category: 'container',
    slot: 'purse',
    tier: 3,
    minFloor: 27,
    weight: 200,
    bulk: 250,
    quality: 'enchanted',
    identified: false,
    description: 'Reinforced with liquid-tight quicksilver seams that lock securely when severed, safeguarding carried fortunes.',
    value: 220,
    itemType: 'container',
    containerConfig: {
      containerType: 'purse',
      maxWeightCapacity: 15000,
      maxBulkCapacity: 2500,
      acceptedCategories: ['currency'],
    },
  },
];
