import type { ItemDefinition } from '../../../engine';

export const COTW_FEET: ItemDefinition[] = [
  {
    id: 'bound_hide_wrappings',
    name: 'Bound Hide Wrappings',
    unidentifiedName: 'Crude Hide Wraps',
    category: 'boots',
    slot: 'feet',
    tier: 1,
    minFloor: 2,
    weight: 600,
    bulk: 800,
    stats: { defenseBonus: 1 },
    identified: true,
    description: 'Basic footwear crafted from tough caribou hide secured with sinew cords.',
    value: 15,
  },
  {
    id: 'crampon_nailed_boots',
    name: 'Crampon-Nailed Boots',
    unidentifiedName: 'Iron-Spiked Boots',
    category: 'boots',
    slot: 'feet',
    tier: 1,
    minFloor: 4,
    weight: 1500,
    bulk: 1600,
    stats: { defenseBonus: 2 },
    identified: false,
    description: 'Heavy boots fitted with forged iron ice-cleats, preventing slippage on glacier ice at the cost of noisy footfalls on stone.',
    value: 35,
  },
  {
    id: 'treadplate_sabatons',
    name: 'Treadplate Sabatons',
    unidentifiedName: 'Heavy Iron Greaves',
    category: 'boots',
    slot: 'feet',
    tier: 2,
    minFloor: 14,
    weight: 3200,
    bulk: 2500,
    stats: { defenseBonus: 5, speedBonus: -2 },
    identified: false,
    description: 'Armored iron sabatons salvaged from dwarven mining automatons. Grants extreme lower-body defense but significantly reduces stride speed.',
    value: 90,
  },
  {
    id: 'sure_step_mine_boots',
    name: 'Sure-Step Mine Boots',
    unidentifiedName: 'Reinforced Cobbled Boots',
    category: 'boots',
    slot: 'feet',
    tier: 3,
    minFloor: 27,
    weight: 2000,
    bulk: 2000,
    stats: { defenseBonus: 4 },
    identified: false,
    description: 'Duergar tunneling boots with spring-damped soles engineered to absorb sudden floor shifts and trigger plates.',
    value: 180,
  },
  {
    id: 'rootless_striders',
    name: 'Rootless Striders',
    unidentifiedName: 'Bark-Woven Buskins',
    category: 'boots',
    slot: 'feet',
    tier: 4,
    minFloor: 36,
    weight: 900,
    bulk: 1100,
    stats: { defenseBonus: 6, speedBonus: 2 },
    quality: 'artifact',
    identified: false,
    description: 'Ethereal bark-fiber boots that skim above the earth, granting immunity to grasping brambles, rooting magic, and subterranean snares.',
    value: 420,
  },
];
