import type { ItemDefinition } from '../../../engine';

export const COTW_HANDS: ItemDefinition[] = [
  {
    id: 'frost_cracked_mitts',
    name: 'Frost-Cracked Mitts',
    unidentifiedName: 'Stiff Hide Mittens',
    category: 'gauntlets',
    slot: 'hands',
    tier: 1,
    minFloor: 2,
    weight: 500,
    bulk: 600,
    stats: { defenseBonus: 1 },
    identified: true,
    description: 'Thick seal-hide mitts cracked by biting glacier winds. Provides modest protection at the cost of delicate finger dexterity.',
    value: 20,
  },
  {
    id: 'duergar_forge_gauntlets',
    name: 'Duergar Forge Gauntlets',
    unidentifiedName: 'Iron-Plated Work Gloves',
    category: 'gauntlets',
    slot: 'hands',
    tier: 2,
    minFloor: 12,
    weight: 1800,
    bulk: 1500,
    stats: { defenseBonus: 3, attackBonus: 2 },
    identified: false,
    description: 'Tough salamander-leather work gloves faced with iron studs. Built for handling molten slag and striking bone-cracking hammer blows.',
    value: 80,
  },
  {
    id: 'glassblowers_grips',
    name: "Glassblower's Grips",
    unidentifiedName: 'Insulated Silk Gloves',
    category: 'gauntlets',
    slot: 'hands',
    tier: 3,
    minFloor: 20,
    weight: 600,
    bulk: 500,
    stats: { defenseBonus: 2, attackBonus: 3 },
    quality: 'enchanted',
    identified: false,
    description: 'Heat-resistant woven quartz gloves used by dwarven siphon-smiths. Greatly enhances the resonance and focus of magical implements.',
    value: 160,
  },
  {
    id: 'leech_skin_gloves',
    name: 'Leech-Skin Gloves',
    unidentifiedName: 'Slick Dark Gloves',
    category: 'gauntlets',
    slot: 'hands',
    tier: 3,
    minFloor: 27,
    weight: 700,
    bulk: 600,
    stats: { defenseBonus: 4 },
    quality: 'enchanted',
    hooks: [
      {
        event: 'onHit',
        chance: 0.35,
        action: {
          type: 'heal',
          amount: 2,
          target: 'self',
        },
        description: '✦ Leech-Skin Gloves siphon fresh life-blood from the struck foe!',
      },
    ],
    identified: false,
    description: 'Sewn from the elastic hide of quicksilver mine parasites. Subtly siphons vital essence on physical impact to mend the wearer’s flesh.',
    value: 260,
  },
  {
    id: 'root_wound_bracers',
    name: 'Root-Wound Bracers',
    unidentifiedName: 'Braided Root Wraps',
    category: 'gauntlets',
    slot: 'hands',
    tier: 4,
    minFloor: 35,
    weight: 1200,
    bulk: 1000,
    stats: { defenseBonus: 5 },
    quality: 'enchanted',
    identified: false,
    description: 'Living taproots of the world-tree woven around the forearms, feeding life into the wearer’s veins over time while rejecting artificial alchemy.',
    value: 390,
  },
];
