import type { ItemDefinition } from '../../../engine';

export const COTW_HEAD: ItemDefinition[] = [
  {
    id: 'brim_wolf_pelt_hood',
    name: 'Brim-Wolf Pelt Hood',
    unidentifiedName: 'Frost-Rimmed Fur Cowl',
    category: 'helmet',
    slot: 'head',
    tier: 1,
    minFloor: 2,
    weight: 900,
    bulk: 1100,
    stats: { defenseBonus: 2 },
    identified: false,
    description: 'Thick winter wolf pelt frosted with eternal rimy chill. Extends the wielder’s dormant giant-blood heritage one zone band deeper into the warming tunnels.',
    value: 30,
  },
  {
    id: 'skraeling_bone_circlet',
    name: 'Skraeling Bone Circlet',
    unidentifiedName: 'Carved Bone Band',
    category: 'helmet',
    slot: 'head',
    tier: 1,
    minFloor: 4,
    weight: 400,
    bulk: 600,
    stats: { defenseBonus: 1, attackBonus: 1 },
    identified: false,
    description: 'A crude circlet strung with etched goblin knuckle-bones and predator fangs, sharpening predatory senses.',
    value: 25,
  },
  {
    id: 'soot_visored_helm',
    name: 'Soot-Visored Helm',
    unidentifiedName: 'Slotted Iron Helm',
    category: 'helmet',
    slot: 'head',
    tier: 2,
    minFloor: 12,
    weight: 2200,
    bulk: 2000,
    stats: { defenseBonus: 5 },
    identified: false,
    description: 'Heavy dwarven forge helmet fitted with narrow mica slits that protect the eyes from choking smoke, blinding glare, and caustic ash.',
    value: 85,
  },
  {
    id: 'zealots_seared_crown',
    name: "Zealot's Seared Crown",
    unidentifiedName: 'Sun-Etched Iron Circlet',
    category: 'helmet',
    slot: 'head',
    tier: 3,
    minFloor: 20,
    weight: 1100,
    bulk: 900,
    stats: { defenseBonus: 4, attackBonus: 3 },
    quality: 'enchanted',
    identified: false,
    description: 'Brand-scorched iron coronet consecrated to Sól. Empowers spellcasting heat and wards against flame, though its radiant aura alerts resting subterranean foes.',
    value: 180,
  },
  {
    id: 'antler_crowned_mask',
    name: 'Antler-Crowned Mask of the Iviðja',
    unidentifiedName: 'Gnarled Horn Mask',
    category: 'helmet',
    slot: 'head',
    tier: 4,
    minFloor: 35,
    weight: 1400,
    bulk: 1600,
    stats: { defenseBonus: 7 },
    quality: 'artifact',
    identified: false,
    description: 'A fearsome wooden visage crowned with petrified stag antlers worn by the sorceress-matriarchs of Járnviðr. Bestows deep communion with roots and mana wells.',
    value: 450,
  },
];
