import type { ItemDefinition } from '../../../engine';

export const COTW_NECK: ItemDefinition[] = [
  {
    id: 'wolf_tooth_thong',
    name: 'Wolf-Tooth Thong',
    unidentifiedName: 'Tooth Necklace',
    category: 'amulet',
    slot: 'neck',
    tier: 1,
    minFloor: 2,
    weight: 100,
    bulk: 150,
    stats: { attackBonus: 1 },
    identified: true,
    description: 'A leather thong strung with wolf fangs, attuning the wearer’s instincts against wild beasts and prowling vermin.',
    value: 25,
  },
  {
    id: 'nisses_pewter_porridge_spoon',
    name: "Nisse's Pewter Porridge-Spoon",
    unidentifiedName: 'Tarnished Pewter Spoon',
    category: 'amulet',
    slot: 'neck',
    tier: 2,
    minFloor: 16,
    weight: 150,
    bulk: 200,
    stats: { defenseBonus: 1 },
    quality: 'enchanted',
    identified: false,
    description: 'A household hearth-charm worn on a hemp twine. Wards food from rot and vermin and stirs warmly when ambushes lurk nearby.',
    value: 110,
  },
  {
    id: 'corpse_chieftains_eye_coin',
    name: "Corpse-Chieftain's Eye-Coin",
    unidentifiedName: 'Heavy Lead Coin',
    category: 'amulet',
    slot: 'neck',
    tier: 2,
    minFloor: 17,
    weight: 120,
    bulk: 100,
    stats: { defenseBonus: 2 },
    quality: 'enchanted',
    identified: false,
    description: 'A blackened burial coin lifted from the hollow skull of a barrow chieftain. Hardens the mind into utter immunity against terror, fear, and dread.',
    value: 140,
  },
  {
    id: 'sun_fragment_pendant',
    name: 'Sun-Fragment Pendant',
    unidentifiedName: 'Glowing Amber Choker',
    category: 'amulet',
    slot: 'neck',
    tier: 3,
    minFloor: 22,
    weight: 200,
    bulk: 150,
    stats: { attackBonus: 3 },
    quality: 'enchanted',
    identified: false,
    description: 'A suspended molten splinter of Sól’s sun-chariot. Imbues strikes with scorching fire and casts permanent warm light into dark depths.',
    value: 220,
  },
  {
    id: 'amber_heart_drop',
    name: 'Amber Heart-Drop',
    unidentifiedName: 'Petrified Tree Tear',
    category: 'amulet',
    slot: 'neck',
    tier: 4,
    minFloor: 35,
    weight: 300,
    bulk: 250,
    stats: { defenseBonus: 4 },
    quality: 'artifact',
    identified: false,
    description: 'A teardrop of primordial fossilized resin from the heart of Yggdrasil. Bestows massive physical vitality and resilience while slowing spiritual flow.',
    value: 460,
  },
];
