import type { ItemDefinition } from '../../../engine';

export const COTW_OFFHAND: ItemDefinition[] = [
  {
    id: 'lashed_driftwood_buckler',
    name: 'Lashed Driftwood Buckler',
    unidentifiedName: 'Crude Wood Buckler',
    category: 'shield',
    slot: 'offHand',
    tier: 1,
    minFloor: 2,
    weight: 1600,
    bulk: 2000,
    stats: { defenseBonus: 2 },
    identified: true,
    description: 'Scavenged driftwood planks bound with raw sinew. Offers rudimentary protection against glancing blows.',
    value: 20,
  },
  {
    id: 'bellows_plate_shield',
    name: 'Bellows-Plate Shield',
    unidentifiedName: 'Riveted Metal Shield',
    category: 'shield',
    slot: 'offHand',
    tier: 2,
    minFloor: 10,
    weight: 4500,
    bulk: 4000,
    stats: { defenseBonus: 5 },
    quality: 'enchanted',
    hooks: [
      {
        event: 'onHit',
        chance: 0.25,
        action: {
          type: 'applyStatus',
          status: 'blindness',
          duration: 2,
        },
        description: '✦ Bellows-Plate Shield vents a choking cloud of soot into the attacker’s eyes!',
      },
    ],
    identified: false,
    description: 'Automaton plating equipped with spring-loaded exhaust vents that spew blinding forge soot when struck.',
    value: 75,
  },
  {
    id: 'sol_shard_focus',
    name: 'Sól-Shard Focus',
    unidentifiedName: 'Gleaming Solar Prism',
    category: 'shield',
    slot: 'offHand',
    tier: 3,
    minFloor: 18,
    weight: 800,
    bulk: 600,
    stats: { defenseBonus: 3, attackBonus: 2 },
    quality: 'enchanted',
    identified: false,
    description: 'A brilliant focus prism capturing radiant sun-chariot glare. Illuminates depths and pierces illusions, but completely suppresses ancestral giant-blood power while held.',
    value: 160,
  },
  {
    id: 'mirror_skulker_facet',
    name: 'Mirror-Skulker Facet',
    unidentifiedName: 'Polished Quartz Buckler',
    category: 'shield',
    slot: 'offHand',
    tier: 3,
    minFloor: 20,
    weight: 2200,
    bulk: 1800,
    stats: { defenseBonus: 4 },
    quality: 'enchanted',
    hooks: [
      {
        event: 'onHit',
        chance: 0.3,
        action: {
          type: 'bonusDamage',
          amount: 4,
          element: 'fire',
        },
        description: '✦ Mirror-Skulker Facet refracts and retaliates with searing beam reflection!',
      },
    ],
    identified: false,
    description: 'A faceted crystalline quartz shield that reflects incoming beams, projectiles, and fire damage back toward hostile casters.',
    value: 190,
  },
  {
    id: 'petrified_world_bark_tower_shield',
    name: 'Petrified World-Bark Tower Shield',
    unidentifiedName: 'Massive Bark Slab',
    category: 'shield',
    slot: 'offHand',
    tier: 4,
    minFloor: 34,
    weight: 7500,
    bulk: 6500,
    stats: { defenseBonus: 11, speedBonus: -2 },
    quality: 'enchanted',
    identified: false,
    description: 'An impenetrable slab of fossilized Yggdrasil taproot. Unsurpassed kinetic defense, though remaining stationary can cause living roots to anchor to the stone beneath.',
    value: 380,
  },
  {
    id: 'draugr_bone_ward',
    name: 'Draugr-Bone Ward',
    unidentifiedName: 'Lashed Ribcage Shield',
    category: 'shield',
    slot: 'offHand',
    tier: 4,
    minFloor: 45,
    weight: 3800,
    bulk: 3500,
    stats: { defenseBonus: 14 },
    quality: 'enchanted',
    identified: false,
    description: 'Interlocked ancient barrow ribs bound in black sinew. Radiates deathly cold and terrifying dread warding against necrotic horrors.',
    value: 550,
  },
];
