import type { ItemDefinition } from '../../../engine';

export const COTW_RINGS: ItemDefinition[] = [
  {
    id: 'bone_carved_band',
    name: 'Bone-Carved Band',
    unidentifiedName: 'Polished Bone Ring',
    category: 'ring',
    slot: 'fingerLeft',
    tier: 1,
    minFloor: 2,
    weight: 20,
    bulk: 25,
    stats: { defenseBonus: 1 },
    identified: true,
    description: 'A smooth ring whittled from mountain sheep horn, providing basic warding.',
    value: 25,
  },
  {
    id: 'rime_signet_of_the_hollows',
    name: 'Rime-Signet of the Hollows',
    unidentifiedName: 'Frost-Etched Silver Ring',
    category: 'ring',
    slot: 'fingerLeft',
    tier: 1,
    minFloor: 6,
    weight: 30,
    bulk: 25,
    stats: { attackBonus: 2 },
    quality: 'enchanted',
    hooks: [
      {
        event: 'onHit',
        chance: 0.25,
        action: {
          type: 'applyStatus',
          status: 'slow',
          duration: 2,
        },
        description: '✦ Rime-Signet of the Hollows saps the foe’s warmth, numbing their limbs!',
      },
    ],
    identified: false,
    description: 'Glacier-chilled silver bearing runic snowflakes. Imbues attacks with frostbite and slows the movement of foes.',
    value: 70,
  },
  {
    id: 'ring_of_the_slag_walker',
    name: 'Ring of the Slag-Walker',
    unidentifiedName: 'Sooty Iron Band',
    category: 'ring',
    slot: 'fingerLeft',
    tier: 2,
    minFloor: 13,
    weight: 45,
    bulk: 30,
    stats: { defenseBonus: 2 },
    quality: 'enchanted',
    identified: false,
    description: 'Forged from vulcanized iron, this band grants unshakeable resistance against molten slag, brimstone, and burning ground surfaces.',
    value: 130,
  },
  {
    id: 'duergar_vault_ring',
    name: 'Duergar Vault-Ring',
    unidentifiedName: 'Engraved Brass Ring',
    category: 'ring',
    slot: 'fingerLeft',
    tier: 2,
    minFloor: 15,
    weight: 40,
    bulk: 30,
    stats: { defenseBonus: 2 },
    quality: 'enchanted',
    identified: false,
    description: 'Bearing the secret cipher of dwarven lock-masters, this ring heightens perception of hollow walls, hidden caches, and secret doors.',
    value: 150,
  },
  {
    id: 'mirror_cut_ring',
    name: 'Mirror-Cut Ring',
    unidentifiedName: 'Sparkling Quartz Ring',
    category: 'ring',
    slot: 'fingerLeft',
    tier: 3,
    minFloor: 23,
    weight: 25,
    bulk: 20,
    stats: { defenseBonus: 3 },
    quality: 'enchanted',
    identified: false,
    description: 'A brilliant gem ring cut into dozens of micro-facets, refracting and rebounding harmful spells back at hostile casters.',
    value: 240,
  },
  {
    id: 'ring_of_the_deep_lode',
    name: 'Ring of the Deep Lode',
    unidentifiedName: 'Tarnished Electrum Band',
    category: 'ring',
    slot: 'fingerLeft',
    tier: 3,
    minFloor: 29,
    weight: 35,
    bulk: 30,
    stats: { defenseBonus: 2, attackBonus: 2 },
    quality: 'enchanted',
    identified: false,
    description: 'Veined with raw subterranean electrum. Pulses warmly when precious gems, raw metals, and hidden treasure hoards are near.',
    value: 300,
  },
  {
    id: 'marrow_gnawed_ring',
    name: 'Marrow-Gnawed Ring',
    unidentifiedName: 'Pitted Bone Loop',
    category: 'ring',
    slot: 'fingerLeft',
    tier: 4,
    minFloor: 46,
    weight: 50,
    bulk: 40,
    quality: 'cursed',
    stats: { attackBonus: 15 },
    identified: false,
    description: 'Gnawed from ancient dragon bone steeped in world-root corruption. Imparts monstrous destructive might, but corrupts the very bedrock beneath the wearer into treacherous sinkholes.',
    value: 750,
  },
];
