import type { ItemDefinition } from '../../../engine';

export const COTW_TORSO: ItemDefinition[] = [
  {
    id: 'layered_fur_jerkin',
    name: 'Layered Fur Jerkin',
    unidentifiedName: 'Thick Fur Vest',
    category: 'armor',
    slot: 'torso',
    tier: 1,
    minFloor: 2,
    weight: 3000,
    bulk: 3500,
    stats: { defenseBonus: 3 },
    identified: true,
    description: 'Supple stitched reindeer hide lined with coarse grease-wool. Light, flexible protection against permafrost winds.',
    value: 25,
  },
  {
    id: 'mammut_hide_brigandine',
    name: 'Mammut-Hide Brigandine',
    unidentifiedName: 'Bone-Studded Leather',
    category: 'armor',
    slot: 'torso',
    tier: 1,
    minFloor: 5,
    weight: 5500,
    bulk: 5000,
    stats: { defenseBonus: 6 },
    identified: false,
    description: 'Tough cured mammut hide reinforced with carved rib-bone splints. Reliable, sturdy protection without encumbering movement.',
    value: 60,
  },
  {
    id: 'cinder_quenched_hauberk',
    name: 'Cinder-Quenched Hauberk',
    unidentifiedName: 'Blackened Mail Shirt',
    category: 'armor',
    slot: 'torso',
    tier: 2,
    minFloor: 12,
    weight: 11000,
    bulk: 7500,
    stats: { defenseBonus: 9 },
    identified: false,
    description: 'Dwarven chainmail quenched in volcanic ash. Deflects heavy crushing and slashing blows, but absorbs ambient furnace heat.',
    value: 130,
  },
  {
    id: 'obsidian_scale_cuirass',
    name: 'Obsidian Scale Cuirass',
    unidentifiedName: 'Glossy Black Scale Mail',
    category: 'armor',
    slot: 'torso',
    tier: 3,
    minFloor: 22,
    weight: 16000,
    bulk: 10000,
    stats: { defenseBonus: 13 },
    quality: 'enchanted',
    identified: false,
    description: 'Meticulously knapped scales of volcanic glass wired over boiled leather. Unyielding against searing flame and sharp blades.',
    value: 280,
  },
  {
    id: 'quicksilver_mesh_shirt',
    name: 'Quicksilver Mesh Shirt',
    unidentifiedName: 'Silvery Mesh Hauberk',
    category: 'armor',
    slot: 'torso',
    tier: 3,
    minFloor: 28,
    weight: 4000,
    bulk: 3000,
    stats: { defenseBonus: 10, speedBonus: 3 },
    quality: 'enchanted',
    identified: false,
    description: 'Woven from cold liquid-mercury filaments that shift with the wearer’s body, granting remarkable agility at the subtle expense of toxic exposure.',
    value: 350,
  },
  {
    id: 'nid_dripping_hauberk',
    name: 'Níð-Dripping Hauberk',
    unidentifiedName: 'Fetid Tar-Crusted Plate',
    category: 'armor',
    slot: 'torso',
    tier: 4,
    minFloor: 45,
    weight: 19000,
    bulk: 12000,
    quality: 'cursed',
    stats: { defenseBonus: 18 },
    hooks: [
      {
        event: 'onHit',
        chance: 0.5,
        action: {
          type: 'bonusDamage',
          amount: 6,
          element: 'acid',
        },
        description: '✦ Níð-Dripping Hauberk retaliates with burning corrosive dragon bile!',
      },
    ],
    identified: false,
    description: 'Heavy plate mail encrusted in boiling venom from the roots of Níðhögg. Retaliates against attackers with acidic tar, but fouls potions and healing draughts.',
    value: 600,
  },
];
