import type { ItemDefinition } from '../../../engine';

export const COTW_WEAPONS: ItemDefinition[] = [
  {
    id: 'mammut_bone_cudgel',
    name: 'Mammut-Bone Cudgel',
    unidentifiedName: 'Heavy Bone Club',
    category: 'weapon',
    slot: 'mainHand',
    tier: 1,
    minFloor: 2,
    weight: 1800,
    bulk: 1400,
    stats: { attackBonus: 4 },
    identified: true,
    description: 'Crude and heavy starter cudgel carved from ancient mammut femur. Delivers crushing blows against unarmored targets.',
    value: 20,
  },
  {
    id: 'rime_bit_chisel',
    name: 'Rime-Bit Chisel',
    unidentifiedName: 'Frost-Etched Chisel',
    category: 'weapon',
    slot: 'mainHand',
    tier: 1,
    minFloor: 2,
    weight: 400,
    bulk: 200,
    stats: { attackBonus: 3, speedBonus: 4 },
    identified: false,
    description: 'Cold-iron glacier tool. Fast and lightweight; cuts deep into frozen ice and brittle foes.',
    value: 25,
  },
  {
    id: 'skraeling_ice_spear',
    name: 'Skraeling Ice-Knapped Spear',
    unidentifiedName: 'Rough Stone Spear',
    category: 'weapon',
    slot: 'mainHand',
    tier: 1,
    minFloor: 3,
    weight: 1600,
    bulk: 2400,
    stats: { attackBonus: 5 },
    twoHanded: true,
    rangedConfig: { range: 2 },
    identified: false,
    description: 'Starved goblin hunting spear with a flint-knapped glacier-ice tip. Has reach to strike approaching enemies at 2 tiles.',
    value: 30,
  },
  {
    id: 'forge_tongue_hammer',
    name: 'Forge-Tongue Hammer',
    unidentifiedName: 'Heavy Smith Hammer',
    category: 'weapon',
    slot: 'mainHand',
    tier: 2,
    minFloor: 10,
    weight: 3500,
    bulk: 2000,
    stats: { attackBonus: 9, speedBonus: -4 },
    identified: false,
    description: 'Dwarven smith hammer that rings with resonant fire. Deals heavy damage to constructs and armored foes, though its swing is slow.',
    value: 65,
  },
  {
    id: 'duergar_slag_tongs',
    name: 'Duergar Slag-Tongs',
    unidentifiedName: 'Long Iron Tongs',
    category: 'weapon',
    slot: 'mainHand',
    tier: 2,
    minFloor: 12,
    weight: 2600,
    bulk: 2200,
    stats: { attackBonus: 7 },
    rangedConfig: { range: 2 },
    identified: false,
    description: 'Long soot-forged tongs with reach 2. Grips incandescent metal safely and can disarm humanoid foes.',
    value: 70,
  },
  {
    id: 'cinder_edge_shortsword',
    name: 'Cinder-Edge Shortsword',
    unidentifiedName: 'Glowing Short Blade',
    category: 'weapon',
    slot: 'mainHand',
    tier: 2,
    minFloor: 14,
    weight: 1200,
    bulk: 800,
    stats: { attackBonus: 8 },
    quality: 'enchanted',
    hooks: [
      {
        event: 'onHit',
        chance: 0.25,
        action: {
          type: 'bonusDamage',
          amount: 3,
          element: 'fire',
        },
        description: '✦ Cinder-Edge Shortsword sears the wound with lingering forge embers!',
      },
    ],
    identified: false,
    description: 'Forge-tempered blade that holds incandescent heat, dealing reliable damage with a chance to inflict searing fire on hit.',
    value: 85,
  },
  {
    id: 'sol_brand_glaive',
    name: 'Sól-Brand Glaive',
    unidentifiedName: 'Sun-Runed Polearm',
    category: 'weapon',
    slot: 'mainHand',
    tier: 3,
    minFloor: 18,
    weight: 3000,
    bulk: 2800,
    twoHanded: true,
    stats: { attackBonus: 12 },
    quality: 'enchanted',
    hooks: [
      {
        event: 'onHit',
        chance: 0.35,
        action: {
          type: 'bonusDamage',
          amount: 5,
          element: 'fire',
        },
        description: '✦ Sól-Brand Glaive flares with sun-chariot fire!',
      },
    ],
    identified: false,
    description: 'Forged from alloy bathed in sun-chariot fire. Inflicts heavy fire damage and casts radiant illumination in subterranean corridors.',
    value: 150,
  },
  {
    id: 'ironwood_bough_stave',
    name: 'Ironwood Bough-Stave',
    unidentifiedName: 'Gnarled Black Staff',
    category: 'weapon',
    slot: 'mainHand',
    tier: 3,
    minFloor: 20,
    weight: 1800,
    bulk: 2000,
    stats: { attackBonus: 6, defenseBonus: 2 },
    quality: 'enchanted',
    identified: false,
    description: 'Petrified black bough carved by troll-wife sorceresses. Channeling conduit that empowers spell damage and weaves mana.',
    value: 175,
  },
  {
    id: 'tarnished_quicksilver_stiletto',
    name: 'Tarnished Quicksilver Stiletto',
    unidentifiedName: 'Liquid-Silver Stiletto',
    category: 'weapon',
    slot: 'mainHand',
    tier: 3,
    minFloor: 26,
    weight: 450,
    bulk: 250,
    stats: { attackBonus: 14, speedBonus: 5 },
    quality: 'enchanted',
    identified: false,
    description: 'Veined with raw mercury from deep cavern lodes. Pierces straight through dense armor, though reckless wielders risk mild toxicity.',
    value: 220,
  },
  {
    id: 'pit_draugr_pick',
    name: 'Pit-Draugr Pick',
    unidentifiedName: 'Calcified Mining Pick',
    category: 'weapon',
    slot: 'mainHand',
    tier: 3,
    minFloor: 28,
    weight: 2800,
    bulk: 1800,
    stats: { attackBonus: 13 },
    identified: false,
    description: 'Heavy steel pick calcified with mineral rind. Ignores enemy armor plating and cleaves into subterranean rock formations.',
    value: 200,
  },
  {
    id: 'heartwood_longsword',
    name: 'Heartwood Longsword',
    unidentifiedName: 'Grain-Carved Longsword',
    category: 'weapon',
    slot: 'mainHand',
    tier: 4,
    minFloor: 34,
    weight: 1500,
    bulk: 1200,
    stats: { attackBonus: 18, defenseBonus: 2 },
    quality: 'enchanted',
    identified: false,
    description: 'Hewn from uncorrupted Yggdrasil heartwood. Incredibly resilient, warding off necrotic rot and retaining pristine razor sharpness.',
    value: 350,
  },
  {
    id: 'rot_porous_cleaver',
    name: 'Rot-Porous Cleaver',
    unidentifiedName: 'Blackened Rotted Great Axe',
    category: 'weapon',
    slot: 'mainHand',
    tier: 4,
    minFloor: 36,
    weight: 5200,
    bulk: 4000,
    twoHanded: true,
    quality: 'cursed',
    stats: { attackBonus: 25 },
    hooks: [
      {
        event: 'onHit',
        chance: 0.4,
        action: {
          type: 'applyStatus',
          status: 'poison',
          duration: 5,
          potency: 4,
        },
        description: '✦ Rot-Porous Cleaver seeps corrupting world-tree decay into the wound!',
      },
    ],
    identified: false,
    description: 'Corrupted great axe saturated in root rot. Delivers devastating armor-cleaving blows, but cursed rot inhibits natural healing.',
    value: 400,
  },
  {
    id: 'nidhogg_fang',
    name: "Níðhögg's Fang",
    unidentifiedName: 'Colossal Dragon Tooth',
    category: 'weapon',
    slot: 'mainHand',
    tier: 4,
    minFloor: 45,
    weight: 1600,
    bulk: 1200,
    quality: 'artifact',
    stats: { attackBonus: 28 },
    hooks: [
      {
        event: 'onKill',
        chance: 1.0,
        action: {
          type: 'heal',
          amount: 8,
          target: 'self',
        },
        description: "✦ Níðhögg's Fang drinks necrotic essence, restoring vitality upon slaying a foe!",
      },
      {
        event: 'onHit',
        chance: 0.35,
        action: {
          type: 'bonusDamage',
          amount: 7,
          element: 'poison',
        },
        description: "✦ Níðhögg's Fang injects primordial dragon venom!",
      },
    ],
    identified: false,
    description: 'A colossal serrated fang shed by Níðhögg itself. Inflicts catastrophic necrotic damage and drains life on kill.',
    value: 1200,
  },
];
