import { describe, it, expect, vi, afterEach } from 'vitest';
import { GameEngine } from '../engine';
import { GameMap } from '../grid/map';
import { TILES } from '../grid/tile';
import { Player } from '../entities/player';
import { cotwManifest } from '../../content/cotw';

/** Floor 1 generated by a fresh engine with the given run seed, while the wall clock reads `clock`. */
function floorLayout(seed: number, clock: number): string {
  vi.spyOn(Date, 'now').mockReturnValue(clock);
  const engine = new GameEngine({
    map: new GameMap(50, 35, TILES.FLOOR),
    player: new Player({ id: 'hero', name: 'Hero', position: { x: 5, y: 5 } }),
    manifest: cotwManifest,
    seed,
    floor: 0,
  });
  engine.changeFloor(1);
  const rows: string[] = [];
  for (let y = 0; y < engine.map.height; y++) {
    let row = '';
    for (let x = 0; x < engine.map.width; x++) row += engine.map.getTile(x, y)?.passable ? '.' : '#';
    rows.push(row);
  }
  vi.restoreAllMocks();
  return rows.join('\n');
}

describe('new floors are seeded from the run, not the wall clock (ARCHITECTURE.md §7.2)', () => {
  afterEach(() => vi.restoreAllMocks());

  it('the same run seed yields the same floor layout whatever the time', () => {
    expect(floorLayout(4242, 1_000)).toBe(floorLayout(4242, 9_999_999));
  });

  it('different run seeds yield different layouts', () => {
    expect(floorLayout(1, 1_000)).not.toBe(floorLayout(2, 1_000));
  });
});
