import { ItemFactory } from '../../../engine';
import type { MonsterDefinition } from '../../../engine';

/**
 * Legacy monster templates preserved for backward compatibility with existing unit tests
 * (e.g. spawner.test.ts, scaling.test.ts, hybridMonsterScaling.test.ts, oath.test.ts).
 */
export const LEGACY_COTW_MONSTERS: Record<string, MonsterDefinition> = {
  giant_rat: {
    id: 'giant_rat',
    name: 'Giant Rat',
    minFloor: 1,
    stats: { hp: 8, maxHp: 8, attack: 4, defense: 1 },
    speed: 120,
    aiType: 'melee',
    resistances: { fire: 'weak', lightning: 'weak' },
    onHitAffliction: {
      type: 'poison',
      chance: 0.25,
      duration: 4,
      potency: 2,
    },
    fleeHealthPercent: 0.0,
    xpValue: 10,
    lootTable: [
      {
        chance: 0.4,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 6) + 1),
      },
      {
        chance: 0.15,
        generate: (id) => ItemFactory.createHealthPotion(id),
      },
    ],
  },
  kobold: {
    id: 'kobold',
    name: 'Kobold',
    minFloor: 1,
    stats: { hp: 10, maxHp: 10, attack: 3, defense: 1 },
    speed: 110,
    aiType: 'coward',
    resistances: { cold: 'weak' },
    fleeHealthPercent: 0.25,
    xpValue: 15,
    lootTable: [
      {
        chance: 0.7,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 10) + 5),
      },
      {
        chance: 0.35,
        generate: (id) => ItemFactory.createDagger(id),
      },
    ],
  },
  goblin: {
    id: 'goblin',
    name: 'Goblin',
    minFloor: 2,
    stats: { hp: 16, maxHp: 16, attack: 5, defense: 2 },
    speed: 105,
    aiType: 'melee',
    resistances: { fire: 'neutral' },
    fleeHealthPercent: 0.2,
    xpValue: 25,
    lootTable: [
      {
        chance: 0.65,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 15) + 10),
      },
      {
        chance: 0.35,
        generate: (id) => ItemFactory.createWoodenShield(id),
      },
      {
        chance: 0.25,
        generate: (id) => ItemFactory.createDagger(id),
      },
    ],
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    minFloor: 5,
    stats: { hp: 18, maxHp: 18, attack: 7, defense: 3 },
    speed: 90,
    aiType: 'melee',
    resistances: { cold: 'resistant', fire: 'weak' },
    statusImmunities: ['poison'],
    fleeHealthPercent: 0.0,
    xpValue: 35,
    tags: ['undead'],
    lootTable: [
      {
        chance: 0.5,
        generate: (id) => ItemFactory.createBroadsword(id),
      },
      {
        chance: 0.4,
        generate: (id) => ItemFactory.createWoodenShield(id),
      },
      {
        chance: 0.3,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 20) + 10),
      },
    ],
  },
  kobold_shaman: {
    id: 'kobold_shaman',
    name: 'Kobold Shaman',
    minFloor: 6,
    stats: { hp: 14, maxHp: 14, attack: 3, defense: 1 },
    speed: 100,
    aiType: 'caster',
    resistances: { cold: 'weak' },
    spells: ['firebolt', 'slow'],
    telegraphedAbility: {
      requiresSpellId: 'firebolt',
      name: 'Hellfire Surge',
      message: 'The {monster} channels primordial hellfire, preparing to unleash Hellfire Surge!',
      pattern: 'blast',
      range: 5,
      radius: 1,
      multiplier: 2.2,
      element: 'fire',
      spawnSurface: 'fire',
      chance: 0.35,
      cooldown: 2,
    },
    spellPreferences: [
      { spellId: 'slow', skipIfTargetHasStatus: 'slow', chance: 0.4 },
      { spellId: 'firebolt' },
    ],
    fleeHealthPercent: 0.3,
    xpValue: 50,
    lootTable: [
      {
        chance: 0.55,
        generate: (id) => ItemFactory.createManaPotion(id),
      },
      {
        chance: 0.45,
        generate: (id) => ItemFactory.createScrollOfTeleport(id),
      },
      {
        chance: 0.35,
        generate: (id) => ItemFactory.createWandOfFireballs(id),
      },
      {
        chance: 0.3,
        generate: (id) => ItemFactory.createScrollOfIdentify(id),
      },
    ],
  },
  wolf: {
    id: 'wolf',
    name: 'Wolf',
    minFloor: 7,
    stats: { hp: 22, maxHp: 22, attack: 8, defense: 2 },
    speed: 125,
    aiType: 'melee',
    resistances: { cold: 'resistant' },
    fleeHealthPercent: 0.15,
    xpValue: 45,
    targetingMode: 'nearest_hostile',
    lootTable: [
      {
        chance: 0.5,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 15) + 5),
      },
      {
        chance: 0.2,
        generate: (id) => ItemFactory.createLeatherArmor(id),
      },
    ],
  },
  ogre: {
    id: 'ogre',
    name: 'Ogre',
    minFloor: 12,
    stats: { hp: 50, maxHp: 50, attack: 12, defense: 4 },
    speed: 75,
    aiType: 'brute',
    statusImmunities: ['paralysis'],
    fleeHealthPercent: 0.0,
    xpValue: 120,
    lootTable: [
      {
        chance: 1.0,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 50) + 40),
      },
      {
        chance: 0.5,
        generate: (id) => ItemFactory.createIronChest(id),
      },
      {
        chance: 0.4,
        generate: (id) => ItemFactory.createChainmail(id),
      },
      {
        chance: 0.3,
        generate: (id) => ItemFactory.createFrostBlade(id),
      },
    ],
  },
  draugr_warrior: {
    id: 'draugr_warrior',
    name: 'Draugr Warrior',
    minFloor: 14,
    stats: { hp: 40, maxHp: 40, attack: 11, defense: 5 },
    speed: 85,
    aiType: 'melee',
    resistances: { cold: 'resistant', fire: 'weak' },
    statusImmunities: ['poison', 'paralysis'],
    onHitAffliction: {
      type: 'slow',
      chance: 0.25,
      duration: 5,
    },
    fleeHealthPercent: 0.0,
    xpValue: 95,
    tags: ['undead'],
    lootTable: [
      {
        chance: 0.6,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 35) + 20),
      },
      {
        chance: 0.3,
        generate: (id) => ItemFactory.createCursedMace(id),
      },
      {
        chance: 0.25,
        generate: (id) => ItemFactory.createIronShield(id),
      },
    ],
  },
  draugr: {
    id: 'draugr',
    name: 'Ancient Draugr',
    minFloor: 14,
    stats: { hp: 40, maxHp: 40, attack: 11, defense: 5 },
    speed: 85,
    aiType: 'melee',
    resistances: { cold: 'resistant', fire: 'weak' },
    statusImmunities: ['poison', 'paralysis'],
    onHitAffliction: {
      type: 'slow',
      chance: 0.25,
      duration: 5,
    },
    fleeHealthPercent: 0.0,
    xpValue: 95,
    tags: ['undead'],
    lootTable: [
      {
        chance: 0.6,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 35) + 20),
      },
      {
        chance: 0.3,
        generate: (id) => ItemFactory.createCursedMace(id),
      },
    ],
  },
  cave_troll: {
    id: 'cave_troll',
    name: 'Cave Troll',
    minFloor: 16,
    stats: { hp: 70, maxHp: 70, attack: 15, defense: 5 },
    speed: 80,
    aiType: 'brute',
    resistances: { fire: 'weak' },
    fleeHealthPercent: 0.0,
    xpValue: 160,
    lootTable: [
      {
        chance: 0.8,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 60) + 40),
      },
      {
        chance: 0.4,
        generate: (id) => ItemFactory.createChainmail(id),
      },
      {
        chance: 0.3,
        generate: (id) => ItemFactory.createIronHelmet(id),
      },
    ],
  },
  fire_giant: {
    id: 'fire_giant',
    name: 'Fire Giant',
    minFloor: 20,
    stats: { hp: 95, maxHp: 95, attack: 18, defense: 7 },
    speed: 85,
    aiType: 'brute',
    resistances: { fire: 'immune', cold: 'weak' },
    statusImmunities: ['paralysis'],
    fleeHealthPercent: 0.0,
    xpValue: 250,
    lootTable: [
      {
        chance: 0.9,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 100) + 50),
      },
      {
        chance: 0.3,
        generate: (id) => ItemFactory.createBroadsword(id),
      },
    ],
  },
  frost_drake: {
    id: 'frost_drake',
    name: 'Frost Drake',
    minFloor: 24,
    stats: { hp: 85, maxHp: 85, attack: 17, defense: 8 },
    speed: 110,
    aiType: 'caster',
    resistances: { cold: 'immune', fire: 'weak' },
    spells: ['slow'],
    spellCooldown: 3,
    fleeHealthPercent: 0.1,
    xpValue: 300,
    lootTable: [
      {
        chance: 0.8,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 120) + 60),
      },
      {
        chance: 0.4,
        generate: (id) => ItemFactory.createFrostBlade(id),
      },
      {
        chance: 0.3,
        generate: (id) => ItemFactory.createHealthPotion(id),
      },
    ],
  },
  dark_sorcerer: {
    id: 'dark_sorcerer',
    name: 'Dark Sorcerer',
    minFloor: 28,
    stats: { hp: 60, maxHp: 60, attack: 10, defense: 5 },
    speed: 100,
    aiType: 'caster',
    resistances: { lightning: 'resistant' },
    spells: ['firebolt', 'lightning_bolt', 'slow'],
    telegraphedAbility: {
      requiresSpellId: 'firebolt',
      name: 'Hellfire Surge',
      message: 'The {monster} channels primordial hellfire, preparing to unleash Hellfire Surge!',
      pattern: 'blast',
      range: 5,
      radius: 1,
      multiplier: 2.2,
      element: 'fire',
      spawnSurface: 'fire',
      chance: 0.35,
      cooldown: 2,
    },
    spellPreferences: [
      { spellId: 'slow', skipIfTargetHasStatus: 'slow', chance: 0.4 },
      { spellId: 'firebolt' },
    ],
    spellCooldown: 2,
    fleeHealthPercent: 0.25,
    xpValue: 350,
    lootTable: [
      {
        chance: 0.6,
        generate: (id) => ItemFactory.createWandOfFireballs(id),
      },
      {
        chance: 0.5,
        generate: (id) => ItemFactory.createManaPotion(id),
      },
      {
        chance: 0.4,
        generate: (id) => ItemFactory.createScrollOfTeleport(id),
      },
    ],
  },
  ancient_wyrm: {
    id: 'ancient_wyrm',
    name: 'Ancient Wyrm',
    minFloor: 35,
    stats: { hp: 140, maxHp: 140, attack: 22, defense: 10 },
    speed: 105,
    aiType: 'caster',
    resistances: { fire: 'resistant', cold: 'resistant' },
    statusImmunities: ['paralysis', 'poison'],
    spells: ['firebolt', 'lightning_bolt'],
    telegraphedAbility: {
      requiresSpellId: 'firebolt',
      name: 'Hellfire Surge',
      message: 'The {monster} channels primordial hellfire, preparing to unleash Hellfire Surge!',
      pattern: 'blast',
      range: 5,
      radius: 1,
      multiplier: 2.2,
      element: 'fire',
      spawnSurface: 'fire',
      chance: 0.35,
      cooldown: 2,
    },
    spellPreferences: [
      { spellId: 'slow', skipIfTargetHasStatus: 'slow', chance: 0.4 },
      { spellId: 'firebolt' },
    ],
    spellCooldown: 3,
    fleeHealthPercent: 0.0,
    xpValue: 500,
    lootTable: [
      {
        chance: 1.0,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 200) + 100),
      },
      {
        chance: 0.6,
        generate: (id) => ItemFactory.createFrostBlade(id),
      },
      {
        chance: 0.5,
        generate: (id) => ItemFactory.createHealthPotion(id),
      },
    ],
  },
  jotun_champion: {
    id: 'jotun_champion',
    name: 'Jotun Champion',
    minFloor: 40,
    stats: { hp: 175, maxHp: 175, attack: 26, defense: 12 },
    speed: 90,
    aiType: 'brute',
    resistances: { cold: 'immune' },
    statusImmunities: ['paralysis'],
    fleeHealthPercent: 0.0,
    xpValue: 650,
    lootTable: [
      {
        chance: 1.0,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 250) + 150),
      },
      {
        chance: 0.6,
        generate: (id) => ItemFactory.createIronChest(id),
      },
      {
        chance: 0.4,
        generate: (id) => ItemFactory.createChainmail(id),
      },
    ],
  },
  shadow_fiend: {
    id: 'shadow_fiend',
    name: 'Shadow Fiend',
    minFloor: 45,
    stats: { hp: 130, maxHp: 130, attack: 24, defense: 9 },
    speed: 130,
    aiType: 'caster',
    resistances: { cold: 'resistant', fire: 'neutral' },
    statusImmunities: ['poison', 'paralysis'],
    onHitAffliction: {
      type: 'slow',
      chance: 0.4,
      duration: 6,
    },
    spells: ['slow', 'lightning_bolt'],
    spellCooldown: 2,
    fleeHealthPercent: 0.0,
    xpValue: 750,
    lootTable: [
      {
        chance: 1.0,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 300) + 200),
      },
      {
        chance: 0.6,
        generate: (id) => ItemFactory.createScrollOfTeleport(id),
      },
      {
        chance: 0.5,
        generate: (id) => ItemFactory.createManaPotion(id),
      },
    ],
  },
  boss_hrungnir: {
    id: 'boss_hrungnir',
    name: 'Hrungnir the Hill Giant Chieftain',
    minFloor: 25,
    stats: { hp: 120, maxHp: 120, attack: 18, defense: 8 },
    speed: 90,
    aiType: 'brute',
    statusImmunities: ['paralysis', 'poison'],
    spells: ['firebolt'],
    telegraphedAbility: {
      requiresSpellId: 'firebolt',
      name: 'Hellfire Surge',
      message: 'The {monster} channels primordial hellfire, preparing to unleash Hellfire Surge!',
      pattern: 'blast',
      range: 5,
      radius: 1,
      multiplier: 2.2,
      element: 'fire',
      spawnSurface: 'fire',
      chance: 0.35,
      cooldown: 2,
    },
    spellPreferences: [
      { spellId: 'slow', skipIfTargetHasStatus: 'slow', chance: 0.4 },
      { spellId: 'firebolt' },
    ],
    spellCooldown: 3,
    fleeHealthPercent: 0.0,
    xpValue: 500,
    lootTable: [
      {
        chance: 1.0,
        generate: (id) =>
          ItemFactory.createQuestRelic(
            id,
            'The Sun-Stone of Freyr',
            'The ancient radiant relic of Freyr, warm to the touch. Returning it to town will bring lasting peace and light.'
          ),
      },
      {
        chance: 1.0,
        generate: (id) => ItemFactory.createPlatinumCoins(id, 5),
      },
      {
        chance: 0.8,
        generate: (id) => ItemFactory.createFrostBlade(id),
      },
    ],
  },
  troll_wife_warlock: {
    id: 'troll_wife_warlock',
    name: 'Troll-Wife Warlock',
    minFloor: 15,
    stats: { hp: 55, maxHp: 55, attack: 12, defense: 6 },
    speed: 95,
    aiType: 'caster',
    resistances: { cold: 'resistant', fire: 'weak' },
    onHitAffliction: {
      type: 'slow',
      chance: 0.3,
      duration: 5,
    },
    spells: ['slow'],
    spellCooldown: 3,
    fleeHealthPercent: 0.2,
    xpValue: 220,
    lootTable: [
      {
        chance: 0.7,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 70) + 30),
      },
      {
        chance: 0.4,
        generate: (id) => ItemFactory.createManaPotion(id),
      },
      {
        chance: 0.25,
        generate: (id) => ItemFactory.createFrostBlade(id),
      },
      {
        chance: 0.5,
        generate: (id) =>
          ItemFactory.createQuestRelic(
            id,
            'Shard of the Hearth-Tear',
            'A splinter of Sól’s stolen sun-chariot, still warm despite the permafrost. The warlocks siphoned its fire to freeze Járnviðr.'
          ),
      },
    ],
  },
  root_wraith: {
    id: 'root_wraith',
    name: 'Root-Wraith',
    minFloor: 27,
    stats: { hp: 90, maxHp: 90, attack: 20, defense: 7 },
    speed: 100,
    aiType: 'melee',
    resistances: { poison: 'immune', cold: 'neutral' },
    statusImmunities: ['poison'],
    onHitAffliction: {
      type: 'poison',
      chance: 0.5,
      duration: 6,
      potency: 4,
    },
    fleeHealthPercent: 0.0,
    xpValue: 340,
    lootTable: [
      {
        chance: 0.8,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 140) + 80),
      },
      {
        chance: 0.35,
        generate: (id) => ItemFactory.createCurePoisonPotion(id),
      },
    ],
  },
  bark_husk_miner: {
    id: 'bark_husk_miner',
    name: 'Bark-Husk Miner',
    minFloor: 30,
    stats: { hp: 110, maxHp: 110, attack: 19, defense: 10 },
    speed: 80,
    aiType: 'brute',
    resistances: { poison: 'resistant' },
    fleeHealthPercent: 0.0,
    xpValue: 380,
    lootTable: [
      {
        chance: 0.85,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 160) + 90),
      },
      {
        chance: 0.3,
        generate: (id) => ItemFactory.createIronChest(id),
      },
    ],
  },
  huldra: {
    id: 'huldra',
    name: 'Huldra of the Hollow Wood',
    minFloor: 8,
    stats: { hp: 35, maxHp: 35, attack: 9, defense: 3 },
    speed: 105,
    aiType: 'caster',
    resistances: { arcane: 'resistant' },
    onHitAffliction: {
      type: 'slow',
      chance: 0.35,
      duration: 4,
    },
    spells: ['slow'],
    spellCooldown: 4,
    fleeHealthPercent: 0.3,
    xpValue: 130,
    lootTable: [
      {
        chance: 0.6,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 50) + 20),
      },
      {
        chance: 0.3,
        generate: (id) => ItemFactory.createHealthPotion(id),
      },
    ],
  },
  nisse: {
    id: 'nisse',
    name: 'Vengeful Nisse',
    minFloor: 6,
    stats: { hp: 18, maxHp: 18, attack: 6, defense: 2 },
    speed: 130,
    aiType: 'melee',
    fleeHealthPercent: 0.4,
    xpValue: 70,
    lootTable: [
      {
        chance: 0.5,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 30) + 10),
      },
      {
        chance: 0.2,
        generate: (id) => ItemFactory.createLockpicks(id),
      },
    ],
  },
  orc: {
    id: 'orc',
    name: 'Orc Warrior',
    minFloor: 3,
    stats: { hp: 28, maxHp: 28, attack: 8, defense: 3 },
    speed: 85,
    aiType: 'melee',
    resistances: { lightning: 'neutral' },
    fleeHealthPercent: 0.15,
    xpValue: 45,
    lootTable: [
      {
        chance: 0.35,
        generate: (id) => ItemFactory.createBroadsword(id),
      },
      {
        chance: 0.25,
        generate: (id) => ItemFactory.createWoodenShield(id),
      },
      {
        chance: 0.4,
        generate: (id, rng) => ItemFactory.createGoldCoins(id, Math.floor(rng() * 20) + 10),
      },
    ],
  },
};
