import type { MonsterDefinition } from '../../../engine';
import { itemDrop } from '../items/makeItem';
import { coinDrop } from '../coinage';

export const MAW_OF_MALICE_MONSTERS: MonsterDefinition[] = [
  {
    id: 'grave_wyrmling',
    name: "Grave-Wyrmling (Níðhögg's Brood)",
    minFloor: 43,
    stats: { hp: 95, maxHp: 95, attack: 21, defense: 7 },
    speed: 120,
    aiType: 'caster',
    resistances: { poison: 'immune', cold: 'resistant', physical: 'resistant' },
    spells: ['slow'],
    telegraphedAbility: {
      requiresSpellId: 'slow',
      name: 'Corrosive Bile Spit',
      message: 'The {monster} rears back its serpentine neck, preparing Corrosive Bile Spit!',
      pattern: 'line',
      range: 5,
      radius: 0,
      multiplier: 2.2,
      element: 'poison',
      spawnSurface: 'acid_pool',
      chance: 0.4,
      cooldown: 2,
    },
    fleeHealthPercent: 0.0,
    xpValue: 520,
    tags: ['dragon', 'wyrm'],
    lootTable: [
      {
        chance: 1.0,
        generate: coinDrop(1),
      },
      {
        chance: 0.4,
        generate: coinDrop(0.5),
      },
    ],
  },
  {
    id: 'nastrond_feaster',
    name: 'Náströnd Feaster',
    minFloor: 44,
    stats: { hp: 115, maxHp: 115, attack: 23, defense: 8 },
    speed: 95,
    aiType: 'melee',
    resistances: { cold: 'resistant', poison: 'immune', physical: 'resistant' },
    statusImmunities: ['poison'],
    hooks: [
      {
        event: 'onHit',
        chance: 0.8,
        action: { type: 'heal', amount: 8, target: 'self' },
        description: 'Náströnd Feaster gorges on flesh, revitalizing its rotting frame!',
      },
    ],
    fleeHealthPercent: 0.0,
    xpValue: 560,
    tags: ['undead', 'fiend'],
    lootTable: [
      {
        chance: 1.0,
        generate: coinDrop(1.25),
      },
      {
        chance: 0.45,
        generate: coinDrop(0.5),
      },
    ],
  },
  {
    id: 'malice_weaver',
    name: 'Malice-Weaver',
    minFloor: 45,
    stats: { hp: 150, maxHp: 150, attack: 25, defense: 9 },
    speed: 110,
    aiType: 'caster',
    resistances: { arcane: 'immune', cold: 'resistant', physical: 'resistant' },
    statusImmunities: ['paralysis', 'blindness'],
    spells: ['slow', 'lightning_bolt'],
    spellCooldown: 2,
    telegraphedAbility: {
      requiresSpellId: 'slow',
      name: 'Psychic Drone',
      message: 'The {monster} vibrates its chitinous limbs in discordant resonance, unleashing Psychic Drone!',
      pattern: 'blast',
      range: 5,
      radius: 2,
      multiplier: 2.4,
      element: 'arcane',
      chance: 0.4,
      cooldown: 3,
    },
    spellPreferences: [
      { spellId: 'slow', skipIfTargetHasStatus: 'slow', chance: 0.4 },
      { spellId: 'lightning_bolt' },
    ],
    fleeHealthPercent: 0.0,
    xpValue: 650,
    tags: ['aberration', 'elite'],
    lootTable: [
      {
        chance: 1.0,
        generate: coinDrop(1.25),
      },
      itemDrop(0.6, 'scroll_teleport'),
      {
        chance: 0.5,
        generate: coinDrop(0.5),
      },
    ],
  },
  {
    id: 'garmling',
    name: 'Garmling',
    minFloor: 43,
    stats: { hp: 45, maxHp: 45, attack: 16, defense: 4 },
    speed: 130,
    aiType: 'melee',
    statusImmunities: ['blindness'],
    targetingMode: 'nearest_hostile',
    fleeHealthPercent: 0.1,
    xpValue: 90,
    tags: ['hound', 'fiend', 'pack', 'fodder'],
    pack: { size: [2, 3] },
    lootTable: [
      {
        chance: 0.7,
        generate: coinDrop(0.5),
      },
    ],
  },
  {
    id: 'hel_warden',
    name: 'Hel Warden',
    minFloor: 46,
    stats: { hp: 180, maxHp: 180, attack: 28, defense: 12 },
    speed: 90,
    aiType: 'brute',
    resistances: { cold: 'immune', physical: 'resistant', poison: 'immune', shadow: 'resistant' },
    statusImmunities: ['paralysis', 'poison', 'slow'],
    onHitAffliction: {
      type: 'slow',
      chance: 0.4,
      duration: 5,
    },
    fleeHealthPercent: 0.0,
    xpValue: 800,
    tags: ['wraith', 'undead', 'elite', 'guardian'],
    lootTable: [
      {
        chance: 1.0,
        generate: coinDrop(1.5),
      },
      {
        chance: 0.6,
        generate: coinDrop(0.5),
      },
    ],
  },
];
