import type { SpellDefinition } from '../../engine';

export const COTW_BLOOD_SPELLS: SpellDefinition[] = [
  {
    id: 'blood_reap',
    name: 'Blood Reap',
    school: 'BloodMagic',
    manaCost: 0,
    volatileEnergyGain: 25,
    maxTargetHpPercent: 0.25,
    requiresKillForEnergy: true,
    corruptionGain: 2,
    element: 'shadow',
    range: 2,
    basePower: 20,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'ray',
    targetingMode: 'ray',
    description:
      'Point-blank execution (1-2 tiles). Deals 20 shadow damage to finish off an almost dead enemy (<= 25% HP). Slaying the victim reaps their vital essence into 25 Volatile Energy (+5 HP, +2 Corruption).',
    visual: {
      archetype: 'projectile',
      color: '#991b1b',
      stepDelayMs: 20,
      travelMode: 'smooth',
    },
    effects: [
      { type: 'damage', amount: 20, element: 'shadow' },
      { type: 'heal', amount: 5, target: 'caster' },
    ],
  },
  {
    id: 'blood_tap',
    name: 'Blood Tap',
    school: 'BloodMagic',
    manaCost: 0,
    volatileEnergyGain: 25,
    maxTargetHpPercent: 0.25,
    requiresKillForEnergy: true,
    corruptionGain: 2,
    element: 'shadow',
    range: 2,
    basePower: 20,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'ray',
    targetingMode: 'ray',
    description:
      'Point-blank execution (1-2 tiles). Deals 20 shadow damage to finish off an almost dead enemy (<= 25% HP). Slaying the victim reaps their vital essence into 25 Volatile Energy (+5 HP, +2 Corruption).',
    visual: {
      archetype: 'projectile',
      color: '#991b1b',
      stepDelayMs: 20,
      travelMode: 'smooth',
    },
    effects: [
      { type: 'damage', amount: 20, element: 'shadow' },
      { type: 'heal', amount: 5, target: 'caster' },
    ],
  },
  {
    id: 'crimson_ward',
    name: 'Crimson Ward',
    school: 'BloodMagic',
    manaCost: 0,
    volatileEnergyCost: 20,
    corruptionGain: 5,
    element: 'shadow',
    range: 0,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description:
      'Coagulates dark blood into an unholy ward granting supernatural quickness for 15 turns. Costs 20 Volatile Energy (+5 Corruption).',
    visual: {
      archetype: 'self_buff',
      color: '#b91c1c',
      durationMs: 220,
    },
    effects: [
      { type: 'applyStatus', statusId: 'haste', duration: 15 },
    ],
  },
  {
    id: 'blood_spear',
    name: 'Blood Spear',
    school: 'BloodMagic',
    manaCost: 0,
    volatileEnergyCost: 25,
    corruptionGain: 8,
    element: 'shadow',
    range: 8,
    basePower: 24,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'ray',
    targetingMode: 'ray',
    description:
      'Hurls an impaling lance of condensed vitriol dealing 24 entropic shadow damage that scales violently with corruption. Costs 25 Volatile Energy (+8 Corruption).',
    visual: {
      archetype: 'projectile',
      color: '#7f1d1d',
      stepDelayMs: 18,
      travelMode: 'smooth',
    },
    effects: [
      { type: 'damage', amount: 24, element: 'shadow' },
    ],
  },
  {
    id: 'exsanguinate',
    name: 'Exsanguinate',
    school: 'BloodMagic',
    manaCost: 0,
    volatileEnergyCost: 35,
    corruptionGain: 15,
    element: 'shadow',
    range: 7,
    basePower: 32,
    areaOfEffect: 1,
    reflects: false,
    targetType: 'tile',
    targetingMode: 'area_burst',
    description:
      'Rips the lifeblood from all foes in a 3x3 area for 32 entropic shadow damage. Costs 35 Volatile Energy (+15 Corruption).',
    visual: {
      archetype: 'projectile_burst',
      color: '#450a0a',
      stepDelayMs: 24,
      burstRadius: 1,
      durationMs: 300,
      travelMode: 'smooth',
    },
    effects: [
      { type: 'damage', amount: 32, element: 'shadow' },
    ],
  },
];
