import type { ItemDefinition } from '../../engine';

export const COTW_ITEMS: ItemDefinition[] = [
  // ==========================================
  // TIER 1 (Floors 1+)
  // ==========================================
  {
    id: 'dagger',
    name: 'Iron Dagger',
    unidentifiedName: 'Small Dagger',
    category: 'weapon',
    slot: 'mainHand',
    tier: 1,
    minFloor: 1,
    weight: 450,
    bulk: 250,
    stats: { attackBonus: 3 },
    identified: true,
    description: 'A sharp, swift iron dagger.',
    value: 15,
  },
  {
    id: 'shortsword',
    name: 'Shortsword',
    unidentifiedName: 'Short Blade',
    category: 'weapon',
    slot: 'mainHand',
    tier: 1,
    minFloor: 1,
    weight: 1200,
    bulk: 800,
    stats: { attackBonus: 5 },
    identified: false,
    description: 'A handy double-edged iron shortsword.',
    value: 30,
  },
  {
    id: 'leather_armor',
    name: 'Studded Leather Armor',
    unidentifiedName: 'Leather Tunic',
    category: 'armor',
    slot: 'torso',
    tier: 1,
    minFloor: 1,
    weight: 4500,
    bulk: 5000,
    stats: { defenseBonus: 4 },
    identified: true,
    description: 'Cured leather reinforced with hardened brass studs.',
    value: 40,
  },
  {
    id: 'wooden_shield',
    name: 'Reinforced Wooden Shield',
    unidentifiedName: 'Round Shield',
    category: 'shield',
    slot: 'offHand',
    tier: 1,
    minFloor: 1,
    weight: 2200,
    bulk: 3000,
    stats: { defenseBonus: 3 },
    identified: true,
    description: 'Sturdy oak banded with iron.',
    value: 25,
  },
  {
    id: 'helmet',
    name: 'Iron Helmet',
    unidentifiedName: 'Metal Cap',
    category: 'helmet',
    slot: 'head',
    tier: 1,
    minFloor: 1,
    weight: 1800,
    bulk: 1500,
    stats: { defenseBonus: 2 },
    identified: true,
    description: 'Protective iron headwear.',
    value: 25,
  },
  {
    id: 'boots',
    name: 'Heavy Leather Boots',
    unidentifiedName: 'Old Boots',
    category: 'boots',
    slot: 'feet',
    tier: 1,
    minFloor: 1,
    weight: 1200,
    bulk: 1800,
    stats: { defenseBonus: 1 },
    identified: true,
    description: 'Thick leather boots built for rugged dungeons.',
    value: 20,
  },
  {
    id: 'health_potion',
    name: 'Minor Health Potion',
    unidentifiedName: 'Red Potion',
    category: 'consumable',
    tier: 1,
    minFloor: 1,
    weight: 250,
    bulk: 150,
    identified: true,
    description: 'A ruby flask that restores 25 Hit Points.',
    value: 20,
    itemType: 'potion',
    potionConfig: {
      potionType: 'health',
      potency: 25,
      effects: [{ type: 'restore_hp', amount: 25 }],
    },
  },
  {
    id: 'mana_potion',
    name: 'Minor Mana Potion',
    unidentifiedName: 'Blue Potion',
    category: 'consumable',
    tier: 1,
    minFloor: 1,
    weight: 250,
    bulk: 150,
    identified: true,
    description: 'A shimmering sapphire vial that restores 20 Mana.',
    value: 25,
    itemType: 'potion',
    potionConfig: {
      potionType: 'mana',
      potency: 20,
      effects: [{ type: 'restore_mana', amount: 20 }],
    },
  },
  {
    id: 'scroll_phase_door',
    name: 'Scroll of Phase Door',
    unidentifiedName: 'Inscribed Vellum',
    category: 'consumable',
    tier: 1,
    minFloor: 1,
    weight: 50,
    bulk: 40,
    identified: true,
    description: 'Instantly shifts position by a short distance.',
    value: 30,
    itemType: 'scroll',
    scrollConfig: {
      spellId: 'phase_door',
    },
  },
  {
    id: 'travel_bread',
    name: 'Travel Bread',
    unidentifiedName: 'Hard Loaf',
    category: 'consumable',
    tier: 1,
    minFloor: 1,
    weight: 300,
    bulk: 250,
    identified: true,
    description: 'Hearth-baked rye bread satisfying hunger on long dungeon explorations.',
    value: 5,
  },

  // Containers (Tier 1)
  {
    id: 'backpack',
    name: 'Adventurer Pack',
    unidentifiedName: 'Large Pack',
    category: 'container',
    slot: 'pack',
    tier: 1,
    minFloor: 1,
    weight: 1500,
    bulk: 2000,
    identified: true,
    description: 'A spacious leather backpack with multiple compartments.',
    value: 35,
    itemType: 'container',
    containerConfig: {
      containerType: 'pack',
      maxWeightCapacity: 30000,
      maxBulkCapacity: 25000,
    },
  },
  {
    id: 'coin_purse',
    name: 'Velvet Coin Purse',
    unidentifiedName: 'Small Pouch',
    category: 'container',
    slot: 'purse',
    tier: 1,
    minFloor: 1,
    weight: 100,
    bulk: 150,
    identified: true,
    description: 'A finely stitched velvet purse with a drawstring for currency.',
    value: 15,
    itemType: 'container',
    containerConfig: {
      containerType: 'purse',
      maxWeightCapacity: 5000,
      maxBulkCapacity: 800,
      acceptedCategories: ['currency'],
    },
  },
  {
    id: 'utility_belt',
    name: 'Wand & Potion Utility Belt',
    unidentifiedName: 'Leather Belt',
    category: 'container',
    slot: 'waist',
    tier: 1,
    minFloor: 1,
    weight: 400,
    bulk: 500,
    identified: true,
    description: 'A sturdy leather belt equipped with quick-draw loops.',
    value: 45,
    itemType: 'container',
    containerConfig: {
      containerType: 'belt',
      maxWeightCapacity: 6000,
      maxBulkCapacity: 2500,
      maxSlots: 4,
      acceptedCategories: ['wand', 'potion', 'scroll'],
    },
  },
  {
    id: 'chest',
    name: 'Ironbound Wooden Chest',
    unidentifiedName: 'Heavy Chest',
    category: 'container',
    tier: 1,
    minFloor: 1,
    weight: 8000,
    bulk: 12000,
    identified: true,
    description: 'A rigid iron-reinforced chest.',
    value: 50,
    itemType: 'container',
    containerConfig: {
      containerType: 'chest',
      maxWeightCapacity: 50000,
      maxBulkCapacity: 35000,
    },
  },

  // ==========================================
  // TIER 2 (Floors 10+)
  // ==========================================
  {
    id: 'broadsword',
    name: 'Steel Broadsword',
    unidentifiedName: 'Heavy Sword',
    category: 'weapon',
    slot: 'mainHand',
    tier: 2,
    minFloor: 10,
    weight: 1600,
    bulk: 1200,
    stats: { attackBonus: 8 },
    identified: false,
    description: 'A well-balanced double-edged steel sword.',
    value: 90,
  },
  {
    id: 'battleaxe',
    name: 'Battleaxe',
    unidentifiedName: 'Heavy Axe',
    category: 'weapon',
    slot: 'mainHand',
    tier: 2,
    minFloor: 10,
    weight: 2200,
    bulk: 1600,
    stats: { attackBonus: 10 },
    identified: false,
    description: 'A formidable two-handed Norse axe.',
    value: 120,
  },
  {
    id: 'frost_blade',
    name: 'Frost Broadsword',
    unidentifiedName: 'Glowing Broadsword',
    category: 'weapon',
    slot: 'mainHand',
    tier: 2,
    minFloor: 10,
    weight: 1500,
    bulk: 1200,
    quality: 'enchanted',
    stats: { attackBonus: 12 },
    identified: false,
    description: 'Runic frost emanates from this enchanted steel blade.',
    value: 200,
  },
  {
    id: 'cursed_mace',
    name: 'Spiked Mace',
    unidentifiedName: 'Dark Spiked Mace',
    category: 'weapon',
    slot: 'mainHand',
    tier: 2,
    minFloor: 10,
    weight: 4000,
    bulk: 2500,
    quality: 'cursed',
    stats: { attackBonus: 2 },
    identified: false,
    description: 'A heavy mace bearing foul demonic runes.',
    value: 10,
  },
  {
    id: 'chainmail',
    name: 'Chainmail Hauberk',
    unidentifiedName: 'Heavy Mail',
    category: 'armor',
    slot: 'torso',
    tier: 2,
    minFloor: 10,
    weight: 12000,
    bulk: 8000,
    stats: { defenseBonus: 8 },
    identified: false,
    description: 'Interlocking steel rings offering superior slash protection.',
    value: 140,
  },
  {
    id: 'iron_shield',
    name: 'Iron Kite Shield',
    unidentifiedName: 'Metal Shield',
    category: 'shield',
    slot: 'offHand',
    tier: 2,
    minFloor: 10,
    weight: 4500,
    bulk: 4500,
    stats: { defenseBonus: 6 },
    identified: false,
    description: 'A solid forged iron shield.',
    value: 80,
  },
  {
    id: 'holy_torch',
    name: 'Holy Torch',
    unidentifiedName: 'Sun-Etched Torch',
    category: 'consumable',
    tier: 2,
    minFloor: 10,
    weight: 400,
    bulk: 200,
    identified: false,
    description: 'A brand blessed at the Temple of Thor. Igniting it sears the undead with holy light.',
    value: 70,
    itemType: 'potion',
    potionConfig: {
      effects: [{ type: 'radial_status', radius: 4, tags: ['undead'], status: 'blindness', duration: 3 }],
    },
  },
  {
    id: 'bat_senses_potion',
    name: 'Bat Senses Potion',
    unidentifiedName: 'Murky Grey Potion',
    category: 'consumable',
    tier: 2,
    minFloor: 10,
    weight: 300,
    bulk: 160,
    identified: false,
    description: 'A bitter draught distilled from cave-bat ichor. Sight fades, but every stirring creature and running trickle becomes unmistakably clear.',
    value: 45,
    itemType: 'potion',
    potionConfig: {
      effects: [{ type: 'apply_status', status: 'sensory_masked', duration: 15 }],
    },
  },
  {
    id: 'regular_health_potion',
    name: 'Regular Health Potion',
    unidentifiedName: 'Crimson Potion',
    category: 'consumable',
    tier: 2,
    minFloor: 10,
    weight: 300,
    bulk: 160,
    identified: false,
    description: 'A potent healing draught restoring 50 Hit Points.',
    value: 50,
    itemType: 'potion',
    potionConfig: {
      potionType: 'health',
      potency: 50,
      effects: [{ type: 'restore_hp', amount: 50 }],
    },
  },
  {
    id: 'regular_mana_potion',
    name: 'Regular Mana Potion',
    unidentifiedName: 'Cerulean Potion',
    category: 'consumable',
    tier: 2,
    minFloor: 10,
    weight: 300,
    bulk: 160,
    identified: false,
    description: 'A distilled magical philter restoring 40 Mana.',
    value: 55,
    itemType: 'potion',
    potionConfig: {
      potionType: 'mana',
      potency: 40,
      effects: [{ type: 'restore_mana', amount: 40 }],
    },
  },
  {
    id: 'scroll_teleport',
    name: 'Scroll of Teleportation',
    unidentifiedName: 'Runic Parchment',
    category: 'consumable',
    tier: 2,
    minFloor: 10,
    weight: 50,
    bulk: 40,
    identified: false,
    description: 'Teleports the reader across the floor.',
    value: 60,
    itemType: 'scroll',
    scrollConfig: {
      spellId: 'teleport',
    },
  },

  // ==========================================
  // TIER 3 (Floors 25+)
  // ==========================================
  {
    id: 'two_handed_sword',
    name: 'Two-Handed Sword',
    unidentifiedName: 'Massive Sword',
    category: 'weapon',
    slot: 'mainHand',
    tier: 3,
    minFloor: 25,
    weight: 3200,
    bulk: 2200,
    stats: { attackBonus: 15 },
    identified: false,
    description: 'A sweeping greatsword delivering devastating cleaved strikes.',
    value: 300,
  },
  {
    id: 'morningstar',
    name: 'Morningstar',
    unidentifiedName: 'Flanged Spiked Club',
    category: 'weapon',
    slot: 'mainHand',
    tier: 3,
    minFloor: 25,
    weight: 2800,
    bulk: 1800,
    stats: { attackBonus: 13 },
    identified: false,
    description: 'A heavy flanged steel morningstar capable of crushing iron armor.',
    value: 260,
  },
  {
    id: 'plate_mail',
    name: 'Plate Mail',
    unidentifiedName: 'Heavy Plate Cuirass',
    category: 'armor',
    slot: 'torso',
    tier: 3,
    minFloor: 25,
    weight: 18000,
    bulk: 11000,
    stats: { defenseBonus: 12 },
    identified: false,
    description: 'Fitted breastplate and tassets engineered to absorb extreme impacts.',
    value: 350,
  },
  {
    id: 'steel_tower_shield',
    name: 'Steel Tower Shield',
    unidentifiedName: 'Tower Shield',
    category: 'shield',
    slot: 'offHand',
    tier: 3,
    minFloor: 25,
    weight: 6500,
    bulk: 5500,
    stats: { defenseBonus: 9 },
    identified: false,
    description: 'A massive curved steel barricade shield.',
    value: 220,
  },
  {
    id: 'wand_lightning',
    name: 'Wand of Lightning',
    unidentifiedName: 'Silver Wand',
    category: 'consumable',
    tier: 3,
    minFloor: 25,
    weight: 350,
    bulk: 200,
    quality: 'enchanted',
    identified: false,
    description: 'Emits devastating bouncing electrical charges.',
    value: 250,
    itemType: 'wand',
    wandConfig: {
      spellId: 'lightning_bolt',
      charges: 8,
      maxCharges: 8,
    },
  },
  {
    id: 'wand_fireballs',
    name: 'Wand of Fireballs',
    unidentifiedName: 'Brass Wand',
    category: 'consumable',
    tier: 3,
    minFloor: 25,
    weight: 400,
    bulk: 250,
    quality: 'enchanted',
    identified: false,
    description: 'Launches fiery explosive orbs.',
    value: 280,
    itemType: 'wand',
    wandConfig: {
      spellId: 'fireball',
      charges: 5,
      maxCharges: 5,
    },
  },

  // ==========================================
  // TIER 4 (Floors 37+)
  // ==========================================
  {
    id: 'mythril_longsword',
    name: 'Mythril Longsword',
    unidentifiedName: 'Luminescent Longsword',
    category: 'weapon',
    slot: 'mainHand',
    tier: 4,
    minFloor: 37,
    weight: 1400,
    bulk: 1000,
    stats: { attackBonus: 20 },
    identified: false,
    description: 'Forged from ethereal elven mythril, incredibly light yet deadly sharp.',
    value: 750,
  },
  {
    id: 'adamantine_greatsword',
    name: 'Adamantine Greatsword',
    unidentifiedName: 'Dark Steel Colossus',
    category: 'weapon',
    slot: 'mainHand',
    tier: 4,
    minFloor: 37,
    weight: 3600,
    bulk: 2600,
    stats: { attackBonus: 26 },
    identified: false,
    description: 'Indestructible adamantine forged in primordial depths.',
    value: 1200,
  },
  {
    id: 'plate_armor',
    name: 'Full Plate Armor',
    unidentifiedName: 'Gleaming Fortress Armor',
    category: 'armor',
    slot: 'torso',
    tier: 4,
    minFloor: 37,
    weight: 22000,
    bulk: 14000,
    stats: { defenseBonus: 16 },
    identified: false,
    description: 'Masterwork articulated plate covering every vulnerable inch.',
    value: 950,
  },
  {
    id: 'aegis_shield',
    name: 'Aegis Shield',
    unidentifiedName: 'Radiant Bulwark',
    category: 'shield',
    slot: 'offHand',
    tier: 4,
    minFloor: 37,
    weight: 5500,
    bulk: 5000,
    stats: { defenseBonus: 13 },
    identified: false,
    description: 'An ancient legendary shield inscribed with runes of absolute warding.',
    value: 650,
  },
  {
    id: 'supreme_health_potion',
    name: 'Supreme Health Potion',
    unidentifiedName: 'Golden Elixir',
    category: 'consumable',
    tier: 4,
    minFloor: 37,
    weight: 300,
    bulk: 180,
    identified: false,
    description: 'A celestial golden elixir that instantly restores 120 Hit Points.',
    value: 180,
    itemType: 'potion',
    potionConfig: {
      potionType: 'health',
      potency: 120,
      effects: [{ type: 'restore_hp', amount: 120 }],
    },
  },

  // ==========================================
  // QUEST RELICS
  // ==========================================
  {
    id: 'sun_stone_freyr',
    name: 'The Sun-Stone of Freyr',
    unidentifiedName: 'Radiant Sun Gem',
    category: 'quest',
    tier: 1,
    minFloor: 1,
    weight: 500,
    bulk: 300,
    quality: 'artifact',
    identified: true,
    description: 'The sacred solar relic stolen by Hrungnir. Restore it to Bjarnarhaven to save the realm.',
    value: 10000,
  },
  {
    id: 'hearth_tear_fragment',
    name: 'Shard of the Hearth-Tear',
    unidentifiedName: 'Warm Splinter of Glass',
    category: 'quest',
    tier: 3,
    minFloor: 15,
    weight: 100,
    bulk: 50,
    quality: 'artifact',
    identified: true,
    description: 'A splinter of Sól’s stolen sun-chariot, still warm despite the permafrost. The troll-wife warlocks of Járnviðr siphoned its fire into the abandoned dwarven forge to freeze the village.',
    value: 500,
  },
];
