import type { MonsterCategoryDefinition } from '../../engine';

/**
 * Monster families for Slayer's Compendium category mastery. Every monster in the
 * bestiary belongs to exactly one family (enforced by `monsterCategories.test.ts`).
 * Common families that fill the early floors need more kills to master than the rare
 * ones met only in the deep.
 */
export const COTW_MONSTER_CATEGORIES: MonsterCategoryDefinition[] = [
  {
    id: 'cotw_undead',
    name: 'The Restless Dead',
    icon: '💀',
    description: 'Draugr, wights, haugbui and every corpse that will not stay in its barrow.',
    masteryKills: 75,
    members: [
      'skeleton',
      'draugr_warrior',
      'draugr',
      'prologue_coven_thrall',
      'deep_lode_pit_draugr',
      'haugbui',
      'cinder_gilded_duergar',
      'kirkegrim',
      'myling',
      'silver_wight',
      'nar',
      'root_bound_berserker',
      'nastrond_feaster',
      'root_wraith',
      'hel_warden',
      'miniboss_rot_matriarch',
      'miniboss_marrow_eater',
    ],
  },
  {
    id: 'cotw_beasts',
    name: 'Beasts & Vermin',
    icon: '🐺',
    description: 'Wolves, rats, burrowers, leeches and the crawling things of the roots.',
    masteryKills: 75,
    members: [
      'giant_rat',
      'wolf',
      'prologue_rime_wolf',
      'brim_howler',
      'garmling',
      'glacier_borer',
      'glod',
      'quicksilver_leech',
      'amber_sap_weeper',
      'yggdrasil_parasite',
      'rotwood_crawler',
    ],
  },
  {
    id: 'cotw_folk',
    name: 'Kin of Men & Goblins',
    icon: '🗡️',
    description: 'Kobolds, goblins, orcs, skraelings, zealots, hags and sorcerers — anything that walks on two legs and thinks.',
    masteryKills: 75,
    members: [
      'kobold',
      'kobold_shaman',
      'goblin',
      'orc',
      'hoarfrost_skraeling',
      'forge_wretch',
      'sol_brand_zealot',
      'winter_hag',
      'dark_sorcerer',
    ],
  },
  {
    id: 'cotw_jotnar',
    name: 'Jötnar & Trolls',
    icon: '🪨',
    description: 'Giants, ogres and troll-kind, from cave trolls to the troll-wife witches of the Ironwood.',
    masteryKills: 50,
    members: [
      'ogre',
      'cave_troll',
      'fire_giant',
      'jotun_champion',
      'troll_wife_warlock',
      'prologue_coven_warlock',
      'ironwood_troll_wife',
      'ividja',
      'miniboss_frost_warden',
    ],
  },
  {
    id: 'cotw_vaettir',
    name: 'Vættir & Spirits',
    icon: '🌫️',
    description: 'Huldra, nisse, fylgjur, phantasms and the other land-spirits that haunt the wild and the deep.',
    masteryKills: 50,
    members: [
      'huldra',
      'huldra_hollow_back',
      'nisse',
      'skratti',
      'fylgja',
      'nacken',
      'choke_damp_phantasm',
      'captive_of_the_chariot',
    ],
  },
  {
    id: 'cotw_constructs',
    name: 'Forged & Formless',
    icon: '⚙️',
    description: 'Automatons, bark-husks, mirror-things and living slag — made, not born.',
    masteryKills: 50,
    members: [
      'bark_husk_miner',
      'bellows_automaton',
      'prismatic_mirror_skulker',
      'slag_amorphous',
      'sun_chariot_warden',
    ],
  },
  {
    id: 'cotw_horrors',
    name: 'Fiends & Horrors',
    icon: '👁️',
    description: 'Shadow fiends and aberrations that crawled up from beneath the roots of the world.',
    // A full clear meets about 21 of them, all on floors 41–50 (20 seeds, measured in faa05ab;
    // tracker 3.5); 40 could never be reached.
    masteryKills: 15,
    members: ['shadow_fiend', 'malice_weaver', 'miniboss_tar_abomination'],
  },
  {
    id: 'cotw_wyrms',
    name: 'Wyrms & Dragonkind',
    icon: '🐉',
    description: 'Drakes, wyrmlings and Níðhögg\'s brood.',
    masteryKills: 30,
    members: ['frost_drake', 'ancient_wyrm', 'grave_wyrmling', 'miniboss_maw_herald', 'nidhogg'],
  },
];
