import type { SpellDefinition } from '../../engine';
import { COTW_BLOOD_SPELLS } from './bloodMagic';

export const COTW_SPELLS: SpellDefinition[] = [
  {
    id: 'magic_arrow',
    name: 'Magic Arrow',
    school: 'Combat',
    manaCost: 3,
    element: 'arcane',
    range: 6,
    basePower: 8,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'ray',
    targetingMode: 'ray',
    description: 'Fires a swift bolt of pure arcane kinetic force.',
    visual: { archetype: 'projectile', color: '#60a5fa', stepDelayMs: 22, travelMode: 'smooth' },
    effects: [{ type: 'damage', amount: 8, element: 'arcane' }],
  },
  {
    id: 'firebolt',
    name: 'Firebolt',
    school: 'Combat',
    manaCost: 5,
    element: 'fire',
    range: 7,
    basePower: 12,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'ray',
    targetingMode: 'ray',
    description: 'Hurls a searing fiery bolt that burns foes on impact.',
    visual: { archetype: 'projectile', color: '#f97316', stepDelayMs: 25, travelMode: 'smooth' },
    effects: [{ type: 'damage', amount: 12, element: 'fire' }],
  },
  {
    id: 'fireball',
    name: 'Fireball',
    school: 'Combat',
    manaCost: 12,
    element: 'fire',
    range: 7,
    basePower: 18,
    areaOfEffect: 1,
    reflects: false,
    targetType: 'tile',
    targetingMode: 'area_burst',
    description: 'Detonates an explosive orb of fire affecting a 3x3 blast area.',
    visual: { archetype: 'projectile_burst', color: '#ef4444', stepDelayMs: 28, burstRadius: 1, durationMs: 280, travelMode: 'smooth' },
    effects: [{ type: 'damage', amount: 18, element: 'fire' }],
  },
  {
    id: 'cold_ray',
    name: 'Cold Ray',
    school: 'Combat',
    manaCost: 6,
    element: 'cold',
    range: 7,
    basePower: 14,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'ray',
    targetingMode: 'ray',
    description: 'Channels a piercing beam of frost, devastating fiery creatures.',
    visual: { archetype: 'projectile', color: '#38bdf8', stepDelayMs: 20, travelMode: 'smooth' },
    effects: [{ type: 'damage', amount: 14, element: 'cold' }],
  },
  {
    id: 'lightning_bolt',
    name: 'Lightning Bolt',
    school: 'Combat',
    manaCost: 9,
    element: 'lightning',
    range: 8,
    basePower: 16,
    areaOfEffect: 0,
    reflects: true,
    targetType: 'ray',
    targetingMode: 'bounce_ray',
    description: 'Fires a crackling lightning bolt that reflects off stone walls.',
    visual: { archetype: 'projectile', color: '#facc15', stepDelayMs: 18, travelMode: 'stepped' },
    effects: [{ type: 'damage', amount: 16, element: 'lightning' }],
  },
  {
    id: 'heal_medium',
    name: 'Heal Medium Wounds',
    school: 'HealingDivination',
    manaCost: 8,
    element: 'healing',
    range: 0,
    basePower: 30,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Invokes divine favor to mend severe flesh wounds.',
    visual: { archetype: 'self_buff', color: '#4ade80', durationMs: 200 },
    effects: [{ type: 'heal', amount: 30 }],
  },
  {
    id: 'teleport',
    name: 'Teleportation',
    school: 'Movement',
    manaCost: 10,
    element: 'arcane',
    range: 0,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Instantly teleports the caster to a random open floor tile on the current map.',
    visual: { archetype: 'teleport', color: '#c084fc', durationMs: 220 },
    effects: [{ type: 'teleport', range: 0, random: true }],
  },
  {
    id: 'phase_door',
    name: 'Phase Door',
    school: 'Movement',
    manaCost: 4,
    element: 'arcane',
    range: 0,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Blinks the caster a short distance away to escape immediate danger.',
    visual: { archetype: 'teleport', color: '#a855f7', durationMs: 180 },
    effects: [{ type: 'teleport', range: 6, random: true }],
  },
  {
    id: 'heal_minor',
    name: 'Heal Minor Wounds',
    school: 'HealingDivination',
    manaCost: 4,
    element: 'healing',
    range: 0,
    basePower: 20,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Restores up to 20 health points to the caster.',
    visual: { archetype: 'self_buff', color: '#86efac', durationMs: 180 },
    effects: [{ type: 'heal', amount: 20 }],
  },
  {
    id: 'identify',
    name: 'Identify',
    school: 'Enchantment',
    manaCost: 8,
    element: 'arcane',
    range: 0,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'inventory_item',
    targetingMode: 'inventory_item',
    description: 'Deciphers ancient Norse runes on an unidentified item.',
    visual: { archetype: 'self_buff', color: '#38bdf8', durationMs: 160 },
    effects: [{ type: 'identify' }],
  },
  {
    id: 'detect_monsters',
    name: 'Detect Monsters',
    school: 'Divination',
    manaCost: 6,
    element: 'arcane',
    range: 0,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Divines the locations of all living creatures across the floor for 30 turns.',
    visual: { archetype: 'self_buff', color: '#60a5fa', durationMs: 180 },
    effects: [{ type: 'reveal', target: 'actors', duration: 30 }],
  },
  {
    id: 'detect_objects',
    name: 'Detect Objects',
    school: 'Divination',
    manaCost: 6,
    element: 'arcane',
    range: 0,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Divines the locations of all treasures and ground items for 30 turns.',
    visual: { archetype: 'self_buff', color: '#facc15', durationMs: 180 },
    effects: [{ type: 'reveal', target: 'items', duration: 30 }],
  },
  {
    id: 'slow',
    name: 'Slow',
    school: 'Enchantment',
    manaCost: 7,
    element: 'arcane',
    range: 6,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'ray',
    targetingMode: 'ray',
    description: 'Burdens the target with magical lethargy, slowing actions by 1.5x.',
    visual: { archetype: 'projectile', color: '#a78bfa', stepDelayMs: 25, travelMode: 'smooth' },
    statusAffliction: {
      type: 'slow',
      duration: 6,
    },
    effects: [{ type: 'applyStatus', statusId: 'slow', duration: 6 }],
  },
  {
    id: 'paralyze',
    name: 'Paralyze',
    school: 'Enchantment',
    manaCost: 12,
    element: 'arcane',
    range: 5,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'ray',
    targetingMode: 'ray',
    description: 'Binds the target in magical stasis, preventing actions.',
    visual: { archetype: 'projectile', color: '#fbbf24', stepDelayMs: 22, travelMode: 'smooth' },
    statusAffliction: {
      type: 'paralysis',
      duration: 3,
    },
    effects: [{ type: 'applyStatus', statusId: 'paralysis', duration: 3 }],
  },
  {
    id: 'clairvoyance',
    name: 'Clairvoyance',
    school: 'Divination',
    manaCost: 14,
    element: 'arcane',
    range: 0,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Flashes divine sight across the entire floor, mapping all corridors and chambers.',
    visual: { archetype: 'screen_flash', color: '#67e8f9', durationMs: 300 },
    effects: [{ type: 'reveal', target: 'map', duration: 1 }],
  },
  ...COTW_BLOOD_SPELLS,
];

export { COTW_BLOOD_SPELLS };


