import type { VaultBlueprint } from '../../engine';
import { SIPHON_ALTAR_TILE, SIPHON_RITUAL_FLOOR, SIPHON_VAULT_ID } from './hostageRitual';

export const COTW_VAULTS: VaultBlueprint[] = [
  {
    id: 'sunken_cistern',
    name: 'The Sunken Cistern',
    description: 'An ancient water reservoir bisected by murky pools and elevated stone catwalks.',
    minFloor: 3,
    layout: [
      '#############',
      '#...~~~.~~~.#',
      '@...~~~.~~~.@',
      '#...~~~.~~~.#',
      '#...M..C..M.#',
      '#...~~~.~~~.#',
      '@...~~~.~~~.@',
      '#...~~~.~~~.#',
      '#############',
    ],
    preferredMonsters: ['giant_rat', 'kobold'],
  },
  {
    id: 'colonnade_arena',
    name: 'The Colonnade Arena',
    description: 'A grand vaulted chamber lined with stone pillars offering tactical cover and sightline breaks.',
    minFloor: 5,
    layout: [
      '#############',
      '#...P.P.P...#',
      '@...P.P.P...@',
      '#...........#',
      '#...M...M...#',
      '#...........#',
      '@...P.P.P...@',
      '#...P.P.P...#',
      '#############',
    ],
    preferredMonsters: ['kobold_shaman', 'skeleton'],
  },
  {
    id: 'fortified_strongroom',
    name: 'The Fortified Strongroom',
    description: 'A reinforced subterranean bunker with iron security slits guarding an opulent treasure vault.',
    minFloor: 8,
    layout: [
      '###########',
      '#BBB###BBB#',
      '#B.......B#',
      '#B..M.C..B#',
      '#B.......B#',
      '###++#++###',
      '#.........#',
      '@.........@',
      '###########',
    ],
    preferredMonsters: ['orc', 'ogre'],
  },
  {
    id: 'sunken_shrine',
    name: 'The Sunken Shrine of Njord',
    description: 'An ancient consecrated pool with stone idols guarding an offering chest.',
    minFloor: 4,
    layout: [
      '#############',
      '#.~~~P.P~~~.#',
      '@.~~~...~~~.@',
      '#.P...C...P.#',
      '#....M.M....#',
      '#.P...C...P.#',
      '@.~~~...~~~.@',
      '#.~~~P.P~~~.#',
      '#############',
    ],
    preferredMonsters: ['giant_rat', 'skeleton'],
  },
  {
    id: 'chasm_treasury',
    name: 'The Abyssal Treasury',
    description: 'A fortified stronghold suspended above an infinite void with barred gates.',
    minFloor: 7,
    layout: [
      '###############',
      '#XXXXX...XXXXX#',
      '#X###BB+BB###X#',
      '@...#..C..#...@',
      '#X#.#.M.M.#.#X#',
      '@...#..C..#...@',
      '#X###BB+BB###X#',
      '#XXXXX...XXXXX#',
      '###############',
    ],
    preferredMonsters: ['orc', 'ogre', 'kobold_shaman'],
  },
  {
    // Guaranteed floor-5 reward room (ARCHITECTURE.md §3, `dungeonArc.ts`'s
    // FLOOR5_RUNE_VAULT_ID) — forced onto floor 5 regardless of the normal
    // random-eligible-vault pool, so it always appears exactly once, guarded
    // by several Rime Hollows monsters. `dungeonArc.ts` adds the Rune of
    // Return to the chest after stamping; `minFloor`/`maxFloor` here are for
    // documentation only, since the forced-placement path bypasses them.
    id: 'floor5_rune_vault',
    name: 'The Frostbound Rune Chamber',
    description: 'A consecrated vault of perpetual frost where towering ice spires and a moat of cracked ice frame the ancient altar dais, guarded by Gálmr the Frost-Warden.',
    minFloor: 5,
    maxFloor: 5,
    minibossId: 'miniboss_frost_warden',
    layout: [
      '#############',
      '#P.~~...~~.P#',
      '@...P.K.P...@',
      '#.~...C...~.#',
      '#.~..M.M..~.#',
      '@...P...P...@',
      '#.~~.....~~.#',
      '#P.~~...~~.P#',
      '#############',
    ],
    preferredMonsters: ['hoarfrost_skraeling', 'skratti', 'brim_howler', 'glacier_borer'],
  },
  {
    id: 'chasm_crossing',
    name: 'The Chasm Crossing',
    description: 'A precarious stone bridge spanning a dizzying abyss, guarded by lurking subterranean predators.',
    minFloor: 12,
    layout: [
      '#############',
      '#...XXXXX...#',
      '#...XXXXX...#',
      '@...XXXXX...@',
      '#...X...X...#',
      '#...X.M.X...#',
      '@...XXXXX...@',
      '#...XXXXX...#',
      '#############',
    ],
    preferredMonsters: ['frost_drake', 'ogre'],
  },
  {
    id: 'floor45_fang_vault',
    name: "The Dragon's Maw Vault",
    description: 'A subterranean sanctum carved into the root-rock of the Maw of Malice, where Víðnir guards Níðhögg’s shed relic fang.',
    minFloor: 45,
    maxFloor: 45,
    minibossId: 'miniboss_maw_herald',
    layout: [
      '###############',
      '#P.~~.....~~.P#',
      '#.~~.......~~.#',
      '@....P.K.P....@',
      '#.~...C.C...~.#',
      '#.~..M...M..~.#',
      '@....P...P....@',
      '#.~~.......~~.#',
      '#P.~~.....~~.P#',
      '###############',
    ],
    preferredMonsters: ['primordial_drake', 'root_rot_abomination', 'void_gazer'],
  },
  {
    id: SIPHON_VAULT_ID,
    name: 'The Siphon Altar of Járnviðr',
    description:
      'An obsidian ritual chamber where troll-wife warlocks prepare captive Bjarnarhaven villagers for blood sacrifice.',
    // Stamped only on the scripted floor (hostageRitual.ts); the `N` markers hold the
    // four captives and `A` is the Siphon Altar tile.
    minFloor: SIPHON_RITUAL_FLOOR,
    maxFloor: SIPHON_RITUAL_FLOOR,
    scriptedOnly: true,
    legend: { A: SIPHON_ALTAR_TILE },
    layout: [
      '###############',
      '#P...B...B...P#',
      '#.N..B.M.B..N.#',
      '@....#####....@',
      '#.M....A....M.#',
      '@....#####....@',
      '#.N..B.M.B..N.#',
      '#P...B...B...P#',
      '###############',
    ],
    preferredMonsters: ['ironwood_troll_wife', 'sol_brand_zealot'],
  },
];


