import type { VaultBlueprint } from '../../engine';

export const COTW_VAULTS: VaultBlueprint[] = [
  {
    id: 'sunken_cistern',
    name: 'The Sunken Cistern',
    description: 'An ancient water reservoir bisected by murky pools and elevated stone catwalks.',
    minFloor: 3,
    layout: [
      '#############',
      '#...~~~.~~~.#',
      '@...~~~.~~~.@',
      '#...~~~.~~~.#',
      '#...M..C..M.#',
      '#...~~~.~~~.#',
      '@...~~~.~~~.@',
      '#...~~~.~~~.#',
      '#############',
    ],
    preferredMonsters: ['giant_rat', 'kobold'],
  },
  {
    id: 'colonnade_arena',
    name: 'The Colonnade Arena',
    description: 'A grand vaulted chamber lined with stone pillars offering tactical cover and sightline breaks.',
    minFloor: 5,
    layout: [
      '#############',
      '#...P.P.P...#',
      '@...P.P.P...@',
      '#...........#',
      '#...M...M...#',
      '#...........#',
      '@...P.P.P...@',
      '#...P.P.P...#',
      '#############',
    ],
    preferredMonsters: ['kobold_shaman', 'skeleton'],
  },
  {
    id: 'fortified_strongroom',
    name: 'The Fortified Strongroom',
    description: 'A reinforced subterranean bunker with iron security slits guarding an opulent treasure vault.',
    minFloor: 8,
    layout: [
      '###########',
      '#BBB###BBB#',
      '#B.......B#',
      '#B..M.C..B#',
      '#B.......B#',
      '###++#++###',
      '#.........#',
      '@.........@',
      '###########',
    ],
    preferredMonsters: ['orc', 'ogre'],
  },
  {
    id: 'sunken_shrine',
    name: 'The Sunken Shrine of Njord',
    description: 'An ancient consecrated pool with stone idols guarding an offering chest.',
    minFloor: 4,
    layout: [
      '#############',
      '#.~~~P.P~~~.#',
      '@.~~~...~~~.@',
      '#.P...C...P.#',
      '#....M.M....#',
      '#.P...C...P.#',
      '@.~~~...~~~.@',
      '#.~~~P.P~~~.#',
      '#############',
    ],
    preferredMonsters: ['giant_rat', 'skeleton'],
  },
  {
    id: 'chasm_treasury',
    name: 'The Abyssal Treasury',
    description: 'A fortified stronghold suspended above an infinite void with barred gates.',
    minFloor: 7,
    layout: [
      '###############',
      '#XXXXX...XXXXX#',
      '#X###BB+BB###X#',
      '@...#..C..#...@',
      '#X#.#.M.M.#.#X#',
      '@...#..C..#...@',
      '#X###BB+BB###X#',
      '#XXXXX...XXXXX#',
      '###############',
    ],
    preferredMonsters: ['orc', 'ogre', 'kobold_shaman'],
  },
  {
    // Guaranteed floor-5 reward room (ARCHITECTURE.md §3, `dungeonArc.ts`'s
    // FLOOR5_RUNE_VAULT_ID) — forced onto floor 5 regardless of the normal
    // random-eligible-vault pool, so it always appears exactly once, guarded
    // by several Rime Hollows monsters. `dungeonArc.ts` adds the Rune of
    // Return to the chest after stamping; `minFloor`/`maxFloor` here are for
    // documentation only, since the forced-placement path bypasses them.
    id: 'floor5_rune_vault',
    name: 'The Frostbound Rune Chamber',
    description: 'A sealed ice-hollow where a carved rune-stone hums beneath a coat of ancient frost, watched over by its guardians.',
    minFloor: 5,
    maxFloor: 5,
    layout: [
      '#############',
      '#...M...M...#',
      '@...........@',
      '#.....C.....#',
      '#...........#',
      '#...........#',
      '@...........@',
      '#...M...M...#',
      '#############',
    ],
    preferredMonsters: ['hoarfrost_skraeling', 'skratti', 'brim_howler', 'glacier_borer'],
  },
  {
    id: 'chasm_crossing',
    name: 'The Chasm Crossing',
    description: 'A precarious stone bridge spanning a dizzying abyss, guarded by lurking subterranean predators.',
    minFloor: 12,
    layout: [
      '#############',
      '#...XXXXX...#',
      '#...XXXXX...#',
      '@...XXXXX...@',
      '#...X...X...#',
      '#...X.M.X...#',
      '@...XXXXX...@',
      '#...XXXXX...#',
      '#############',
    ],
    preferredMonsters: ['frost_drake', 'ogre'],
  },
];

