import type { SpellDefinition } from '../../engine';

export const WARCRAFT_SPELLS: SpellDefinition[] = [
  {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    school: 'Combat',
    manaCost: 14,
    element: 'lightning',
    range: 8,
    basePower: 22,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'ray',
    targetingMode: 'ray',
    description: 'Discharges an electric shock that leaps across multiple enemy targets.',
    visual: { archetype: 'chain', color: '#38bdf8', stepDelayMs: 15, durationMs: 160 },
    effects: [
      { type: 'damage', amount: '3d6+6', element: 'lightning' },
      { type: 'chain', maxHops: 3, hopRange: 4, damageDecay: 0.25 },
    ],
  },
  {
    id: 'holy_light',
    name: 'Holy Light',
    school: 'HealingDivination',
    manaCost: 8,
    element: 'healing',
    range: 0,
    basePower: 35,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Invokes the Light of Lordaeron to restore vitality.',
    visual: { archetype: 'self_buff', color: '#fef08a', durationMs: 240 },
    effects: [{ type: 'heal', amount: 35 }],
  },
  {
    id: 'bloodlust',
    name: 'Bloodlust',
    school: 'Enchantment',
    manaCost: 10,
    element: 'arcane',
    range: 0,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Fills the caster with berserker battle fury.',
    visual: { archetype: 'self_buff', color: '#dc2626', durationMs: 240 },
    effects: [{ type: 'applyStatus', statusId: 'haste', duration: 8, potency: 1 }],
  },
  {
    id: 'fel_fireball',
    name: 'Fel Fireball',
    school: 'Combat',
    manaCost: 16,
    element: 'fire',
    range: 7,
    basePower: 26,
    areaOfEffect: 1,
    reflects: false,
    targetType: 'tile',
    targetingMode: 'area_burst',
    description: 'Hurls an orb of demonic fel flame that explodes in a 3x3 blast area.',
    visual: { archetype: 'projectile_burst', color: '#84cc16', stepDelayMs: 26, burstRadius: 1, durationMs: 280, travelMode: 'smooth' },
    effects: [
      { type: 'damage', amount: '4d6+4', element: 'fire' },
      { type: 'applyStatus', statusId: 'burning', duration: 3, potency: 4 },
    ],
  },
  {
    id: 'frost_nova',
    name: 'Frost Nova',
    school: 'Combat',
    manaCost: 12,
    element: 'cold',
    range: 6,
    basePower: 16,
    areaOfEffect: 1,
    reflects: false,
    targetType: 'tile',
    targetingMode: 'area_burst',
    description: 'Freezes surrounding foes with a sudden blast of frost.',
    visual: { archetype: 'direct_burst', color: '#38bdf8', burstRadius: 1, durationMs: 260 },
    effects: [
      { type: 'damage', amount: 16, element: 'cold' },
      { type: 'applyStatus', statusId: 'slow', duration: 4 },
    ],
  },
  {
    id: 'blink',
    name: 'Blink',
    school: 'Movement',
    manaCost: 6,
    element: 'arcane',
    range: 6,
    basePower: 0,
    areaOfEffect: 0,
    reflects: false,
    targetType: 'self',
    targetingMode: 'self',
    description: 'Instantly teleports the caster a short distance away.',
    visual: { archetype: 'teleport', color: '#c084fc', durationMs: 180 },
    effects: [{ type: 'teleport', range: 6, random: true }],
  },
];
