export type TerrainSpriteKey =
  | 'wall'
  | 'floor'
  | 'door_closed'
  | 'door_open'
  | 'stairs_up'
  | 'stairs_down'
  | 'trap'
  | 'secret_door'
  // Town terrain variants
  | 'wall_town'
  | 'floor_town'
  | 'floor_town_outdoor'
  | 'wall_town_temple'
  | 'floor_town_temple'
  | 'wall_town_smithy'
  | 'floor_town_smithy'
  | 'wall_town_shop'
  | 'floor_town_shop'
  | 'wall_town_bank'
  | 'floor_town_bank'
  | 'hearth_fire';

export type EntitySpriteKey =
  | 'player'
  | 'player_female'
  | 'kobold'
  | 'skeleton'
  | 'giant_rat'
  | 'orc'
  | 'giant_boss'
  | 'shopkeeper'
  | 'townsperson'
  | 'priest'
  | 'sage'
  | 'banker'
  | 'guard'
  // Monster Archetype Families
  | 'dragon'
  | 'wyrm'
  | 'aberration'
  | 'fiend'
  | 'dragon_boss'
  | 'wight'
  | 'zombie'
  | 'wraith'
  | 'spectral'
  | 'spirit'
  | 'fae'
  | 'imp'
  | 'bone_horror'
  | 'construct'
  | 'slime'
  | 'golem'
  | 'hound'
  | 'salamander'
  | 'parasite'
  | 'insect'
  | 'spider'
  | 'wolf'
  | 'dwarf'
  | 'hag'
  | 'zealot'
  | 'cultist'
  | 'troll'
  // Collision-breaking variants (distinct archetypes that would otherwise share
  // a broader family's icon — see sprite-mapper.ts's DEFAULT_TAG_SPRITE_ORDER)
  | 'sorcerer'
  | 'giant'
  | 'giant_fire'
  | 'shadow'
  | 'ghost'
  | 'bound_spirit'
  | 'dragon_elder';

export type ItemSpriteKey =
  | 'broadsword'
  | 'leather_armor'
  | 'wooden_shield'
  | 'health_potion'
  | 'gold_coins'
  | 'dagger'
  | 'helmet'
  | 'boots'
  | 'backpack'
  | 'purse'
  | 'cursed_mace'
  | 'chest'
  | 'belt'
  | 'travel_bread'
  // Expanded Equipment & Consumables
  | 'iron_armor'
  | 'iron_shield'
  | 'mace'
  | 'battleaxe'
  | 'warhammer'
  | 'bow'
  | 'ring'
  | 'amulet'
  | 'cloak'
  | 'gauntlets'
  | 'bracers'
  | 'mana_potion'
  | 'scroll'
  | 'gem'
  | 'key'
  | 'torch'
  | 'rune_stone';

export type SpriteKey = TerrainSpriteKey | EntitySpriteKey | ItemSpriteKey;

export interface AtlasCoords {
  col: number;
  row: number;
}

